//! Generated `.nam` WaveNet fixtures (D-19.1's parity and performance rows), ported from the
//! S-1 spike's constrained-init, RMS-calibrated generator (`spikes/s1-nam-inference`).
//!
//! D-19.1's real hazard: naive random weights can leave a network's output near-silent or
//! divergent, which makes an RMS-relative error metric meaningless. [`generate`] guards against
//! this the same way the S-1 spike did — constrained (fan-in-scaled) initialisation to keep
//! activations in a sane range, then a calibration pass that rescales `head_scale` to hit a
//! target output RMS and verifies the result is neither silent nor exploding before returning it.

mod a2_infer;
mod infer;
mod lstm_infer;

/// Bumped by hand whenever anything in this module changes the *bytes* it generates for a given
/// `(shape, seed)` — a weight-layout change, a different constrained-init scale, a new metadata
/// field, a change to the calibration pass.
///
/// Its one consumer is [`crate::library`]'s corpus cache key: that cache stores `.nam` files this
/// module produced, under a key that used to fold in only `library`'s own composition constants,
/// so a change *here* left a warm `target/namir-fixtures-cache` serving the previous layout's
/// files indefinitely — and nothing in `cargo test` re-validates a cached corpus, so the symptom
/// was a `namir-library` scan test failing against files the current parser rejects, with no hint
/// that a stale cache was the cause. Bumping this invalidates every cached corpus built from an
/// older generator.
///
/// Version 1 is the pre-existing generator (this constant was introduced, not bumped, when the
/// cache key first started folding it in).
pub const GENERATOR_VERSION: u32 = 1;

use rand::Rng;
use rand::SeedableRng;
use serde::{Deserialize, Serialize};
use std::error::Error;
use std::fmt;

/// A generated `.nam` WaveNet fixture: this crate's own JSON-serializable mirror of
/// `namir_nam::file::NamFile`, kept as an independent type deliberately (see this module's doc
/// comment on cross-implementation parity) rather than depending on `namir-nam` for it.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct NamModel {
    /// The exporter's format version string this fixture claims.
    pub version: String,
    /// Always `"WaveNet"` for fixtures generated by this module.
    pub architecture: String,
    /// The WaveNet topology and weights layout.
    pub config: WaveNetConfig,
    /// The flat weight vector, laid out per `build_weights`'s doc comment.
    pub weights: Vec<f32>,
    /// The sample rate this fixture declares (always `SAMPLE_RATE`).
    pub sample_rate: u32,
    /// Display-only metadata identifying this as a generated fixture.
    pub metadata: NamMetadata,
}

/// The WaveNet model's top-level configuration: its stack of layer arrays plus output scaling.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct WaveNetConfig {
    /// The model's layer-array stack, in evaluation order.
    pub layers: Vec<LayerArrayConfig>,
    /// Output scaling applied after the head; the value `generate`'s calibration pass rescales.
    pub head_scale: f32,
    /// Opaque head configuration; always `None` for fixtures generated by this module.
    pub head: Option<serde_json::Value>,
}

/// One WaveNet layer array's hyperparameters; field names mirror the real `.nam` exporter schema
/// (see `namir_nam::file::LayerArrayConfig`).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LayerArrayConfig {
    /// Number of input channels into this layer array.
    pub input_size: usize,
    /// Number of conditioning channels feeding this layer array.
    pub condition_size: usize,
    /// Number of channels feeding the array's head.
    pub head_size: usize,
    /// Number of channels each layer in the array carries internally.
    pub channels: usize,
    /// Convolution kernel width shared by every layer in the array.
    pub kernel_size: usize,
    /// Per-layer dilation factors, one entry per layer in the array.
    pub dilations: Vec<usize>,
    /// Activation function name; fixtures generated by this module always use `"Tanh"`.
    pub activation: String,
    /// Whether the layer array uses gated activation; fixtures generated by this module always
    /// set this `false`.
    pub gated: bool,
    /// Whether the array's head applies a bias term.
    pub head_bias: bool,
}

/// Display-only metadata identifying a generated fixture as such; see `build_model`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct NamMetadata {
    /// The model's display name.
    pub name: String,
    /// Author/creator credit; always `"namir-fixtures"` for generated fixtures.
    pub modeled_by: String,
    /// Modeled gear's make/model/type, as free text; always `"amp"` for generated fixtures.
    pub gear_type: String,
    /// Modeled gear's tone type, as free text; always `"clean"` for generated fixtures.
    pub tone_type: String,
    /// Free-text description explaining these are synthetic, unmusical weights.
    pub description: String,
}

/// A thin public re-export of `infer::run`, exposed *specifically* as a cross-crate numeric
/// parity oracle for `namir-nam`'s independently-written WaveNet implementation: two
/// from-scratch Rust ports of the same algorithm agreeing tightly is strong evidence neither has
/// a subtle bug. This does not change `infer.rs`'s own stated scope — it still only ever needs to
/// handle this crate's own generator output (ungated, `Tanh`-only), so no new capability is added
/// here, only visibility of the one function that already existed.
pub fn reference_infer(model: &NamModel, input: &[f32]) -> Vec<f32> {
    infer::run(model, input)
}

/// A thin public re-export of `a2_infer::run`, exposed *specifically* as a cross-crate numeric
/// parity oracle for `namir-nam`'s independently-written A2 implementation — the A2 counterpart of
/// [`reference_infer`]; see that function's doc comment, which applies here unchanged except for
/// architecture. As with `reference_infer`, this does not change `a2_infer.rs`'s own stated scope:
/// it only ever needs to handle this crate's own generator output (ungated, `LeakyReLU`-only,
/// single layer array), so no new capability is added here, only visibility.
pub fn reference_infer_a2(model: &A2Model, input: &[f32]) -> Vec<f32> {
    a2_infer::run(model, input)
}

/// A generated `.nam` LSTM fixture: this crate's own JSON-serializable mirror of
/// `namir_nam::LstmFile` (see this module's doc comment on why that's kept independent). Field
/// names match the real exporter schema, same as [`NamModel`]'s WaveNet fields.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LstmModel {
    /// The exporter's format version string this fixture claims.
    pub version: String,
    /// Always `"LSTM"` for fixtures generated by this module.
    pub architecture: String,
    /// The LSTM topology.
    pub config: LstmConfig,
    /// The flat weight vector, laid out per `build_lstm_weights`'s doc comment — no trailing
    /// scalar, unlike [`NamModel`]'s `head_scale`.
    pub weights: Vec<f32>,
    /// The sample rate this fixture declares (always `SAMPLE_RATE`).
    pub sample_rate: u32,
    /// Display-only metadata identifying this as a generated fixture.
    pub metadata: NamMetadata,
}

/// One LSTM model's top-level configuration; field names mirror the real `.nam` exporter schema
/// (see `namir_nam::LstmConfigJson`).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LstmConfig {
    /// Number of stacked LSTM cells.
    pub num_layers: usize,
    /// Width of the vector fed to the first cell; fixtures generated by this module always use
    /// `1` (`namir-nam`'s scope restriction — the raw mono signal, no conditioning).
    pub input_size: usize,
    /// Width of every cell's hidden (and cell) state.
    pub hidden_size: usize,
    /// Number of physical audio input channels; fixtures generated by this module always use
    /// `1`.
    pub in_channels: usize,
    /// Number of physical audio output channels; fixtures generated by this module always use
    /// `1`.
    pub out_channels: usize,
}

/// A thin public re-export of `lstm_infer::run`, exposed *specifically* as a cross-crate numeric
/// parity oracle for `namir-nam`'s own LSTM implementation — the LSTM counterpart of
/// [`reference_infer`]; see that function's doc comment, which applies here unchanged except for
/// architecture and for the paragraph below.
///
/// **What "parity oracle" is worth here, stated precisely** (this doc comment used to call
/// `namir-nam`'s LSTM implementation "independently-written" with respect to this one, which was
/// false as written): `lstm_infer.rs` was originally written from `namir-nam`'s *reading* of the
/// `.nam` LSTM format, not from the format's own source, so agreement between the two could not
/// rule out a misreading they shared. M14 re-derived it from `NeuralAmpModelerCore`'s
/// `NAM/lstm.h`/`NAM/lstm.cpp` at the pinned commit, fact by fact with citations, and pinned each
/// fact to hand-computed arithmetic in that module's own tests. Two things are still true and
/// worth keeping in view: the re-derivation was not blind (its author had seen the earlier port),
/// and the only *external* LSTM evidence this project holds — `namir-nam`'s
/// `tests/golden_reference.rs` `lstm_tiny` render — is a one-layer model, so the multi-layer
/// facts rest on `lstm_infer.rs`'s analytic tests rather than on a real reference render.
pub fn reference_infer_lstm(model: &LstmModel, input: &[f32]) -> Vec<f32> {
    lstm_infer::run(model, input)
}

impl NamModel {
    /// Serializes to pretty-printed `.nam` JSON bytes. Infallible in practice — every field is a
    /// plain serializable type — hence the `expect` rather than a `Result`.
    pub fn to_json_bytes(&self) -> Vec<u8> {
        serde_json::to_vec_pretty(self).expect("NamModel always serializes")
    }

    /// Parses `.nam` JSON bytes back into a `NamModel`, the inverse of `to_json_bytes`.
    pub fn from_json_bytes(bytes: &[u8]) -> Result<Self, serde_json::Error> {
        serde_json::from_slice(bytes)
    }
}

impl LstmModel {
    /// Serializes to pretty-printed `.nam` JSON bytes; see `NamModel::to_json_bytes`.
    pub fn to_json_bytes(&self) -> Vec<u8> {
        serde_json::to_vec_pretty(self).expect("LstmModel always serializes")
    }

    /// Parses `.nam` JSON bytes back into an `LstmModel`, the inverse of `to_json_bytes`.
    pub fn from_json_bytes(bytes: &[u8]) -> Result<Self, serde_json::Error> {
        serde_json::from_slice(bytes)
    }
}

/// The four WaveNet architecture shapes NFR-PERF-010's performance fixtures need (D-19.1:
/// "Realistic architecture shapes... Cost follows topology, not weight values").
///
/// **Assumption, not a researched fact:** only "standard" comes from a verified source (the S-1
/// spike's `generate_fixture.rs`, itself confirmed against `neural-amp-modeler`'s
/// `get_wavenet_config`). The real NAM ecosystem's lite/feather/nano channel counts are not
/// specified anywhere in this repo's docs, so lite/feather/nano below are *this crate's own*
/// progressive down-scaling of "standard" — chosen only to give a plausible, monotonically
/// decreasing relative cost across the four shapes, and must not be read as verified against any
/// real NAM preset. If real preset numbers surface later, replace these, not the topology shape.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WaveNetShape {
    /// The S-1 spike's verified shape: 2 layer arrays, channels 16/8, kernel_size 3, 10 dilated
    /// layers each (dilations 1..512). Confirmed against `neural-amp-modeler`'s
    /// `get_wavenet_config` (v0.10.0) — see `spikes/s1-nam-inference/README.md`.
    Standard,
    /// Unverified down-scaling of `Standard` (see the enum doc comment): channels 12/6, 8 layers.
    Lite,
    /// Unverified down-scaling of `Standard`: channels 8/4, 6 layers.
    Feather,
    /// Unverified down-scaling of `Standard`: channels 4/2, 4 layers.
    Nano,
}

/// Fixed 2-layer-array topology parameters for one [`WaveNetShape`]: `channels1` feeds
/// `channels2` via `head_size1`, which the chaining invariant (checked in [`generate`]) requires
/// to equal `channels2`.
struct ShapeParams {
    channels1: usize,
    channels2: usize,
    layers: usize,
}

/// The placeholder `head_scale` [`generate`] builds its weights with, before the calibration pass
/// replaces it. Named so [`uncalibrated_weights`] reproduces `generate`'s first pass exactly
/// rather than by repeating a literal.
const BASE_HEAD_SCALE: f32 = 0.02;

/// Exactly the weight vector [`generate`]'s **first** pass produces for `(shape, seed)`: seeded,
/// constrained-init, with [`BASE_HEAD_SCALE`] still in the trailing slot. No calibration, and so
/// no inference — this is RNG and arithmetic only, microseconds for the small shapes, which is
/// what makes it usable where calling `generate` would not be.
///
/// Exposed for [`crate::library`]'s cache key, and worth the exposure for a reason a version
/// constant cannot cover: this fingerprints the weight *layout and initialisation* themselves, so
/// reordering `build_weights`' sections or changing a fan-in scale invalidates a cached corpus
/// mechanically — no hand-bump of [`GENERATOR_VERSION`] required, and no inference pass paid on
/// every cache hit. What it does not see is a change confined to the calibration pass or to the
/// metadata strings; those still need the constant bumped.
pub fn uncalibrated_weights(shape: WaveNetShape, seed: u64) -> Vec<f32> {
    let specs = shape.layer_configs();
    let mut rng = rand_pcg::Pcg64::seed_from_u64(seed);
    build_weights(&specs, &mut rng, BASE_HEAD_SCALE)
}

/// The topology [`generate`] builds for `shape`, before any weights or calibration — cheap to
/// compute (no RNG, no inference pass) and fully determined by `shape`.
///
/// Exposed for one purpose: a caller that *caches* generated `.nam` files can fold this into its
/// cache key and have a change to a shape's topology invalidate that cache mechanically, without
/// depending on someone remembering to bump [`GENERATOR_VERSION`] by hand. See
/// [`crate::library`]'s `cache_signature`, its only caller.
pub fn shape_signature(shape: WaveNetShape) -> Vec<LayerArrayConfig> {
    shape.layer_configs()
}

impl WaveNetShape {
    fn params(self) -> ShapeParams {
        match self {
            WaveNetShape::Standard => ShapeParams {
                channels1: 16,
                channels2: 8,
                layers: 10,
            },
            WaveNetShape::Lite => ShapeParams {
                channels1: 12,
                channels2: 6,
                layers: 8,
            },
            WaveNetShape::Feather => ShapeParams {
                channels1: 8,
                channels2: 4,
                layers: 6,
            },
            WaveNetShape::Nano => ShapeParams {
                channels1: 4,
                channels2: 2,
                layers: 4,
            },
        }
    }

    fn name(self) -> &'static str {
        match self {
            WaveNetShape::Standard => "standard",
            WaveNetShape::Lite => "lite",
            WaveNetShape::Feather => "feather",
            WaveNetShape::Nano => "nano",
        }
    }

    /// The two `LayerArrayConfig`s for this shape: array 1 rechannels the mono input to
    /// `channels1` and hands its `head_size` (== `channels2`) forward as array 2's `channels`
    /// (the trunk/head chaining invariant `PreparedWaveNet::from_nam_file`-style loaders check).
    fn layer_configs(self) -> Vec<LayerArrayConfig> {
        let p = self.params();
        let dilations: Vec<usize> = (0..p.layers).map(|i| 1usize << i).collect();
        vec![
            LayerArrayConfig {
                input_size: 1,
                condition_size: 1,
                head_size: p.channels2,
                channels: p.channels1,
                kernel_size: 3,
                dilations: dilations.clone(),
                activation: "Tanh".to_string(),
                gated: false,
                head_bias: false,
            },
            LayerArrayConfig {
                input_size: p.channels1,
                condition_size: 1,
                head_size: 1,
                channels: p.channels2,
                kernel_size: 3,
                dilations,
                activation: "Tanh".to_string(),
                gated: false,
                head_bias: true,
            },
        ]
    }
}

/// The `hidden_size`/`num_layers` progressions [`generate_lstm`] can produce.
///
/// **Verified against real NAM LSTM models (2026-08-08).** These three shapes were originally this
/// crate's own guesses, disclaimed here as "not verified against any real NAM LSTM preset" because
/// no researched LSTM shape was available to confirm against — unlike [`WaveNetShape::Standard`],
/// which has always cited `neural-amp-modeler`'s own `get_wavenet_config`. That disclaimer is now
/// retired: a set of 67 reference LSTM models published by NAM's author was examined directly
/// (`docs/manual-tests/fr-nam-020-real-lstm-models.md` records the set, its provenance and its licence status), and it
/// is a systematic sweep of `num_layers` 1–4 against `hidden_size` 1–12, 16, 20, 24, 28, 32, every
/// one at `input_size: 1` and 48 kHz. **All three shapes below exist in that sweep** — `Standard`
/// is its `LSTM-2-032`, `Small` its `LSTM-1-016`, `Tiny` its `LSTM-1-004` — so the guessed numbers
/// turned out to be real ones and need no replacing.
///
/// What that does and does not buy: these are confirmed to be *shapes the ecosystem actually
/// ships*, so a fixture built from them exercises a real configuration rather than an invented one.
/// It is not a numerical claim — the weights here are still generated per D-19.1, and no real LSTM
/// model has yet been compared numerically against a reference implementation's render. See the
/// manual test for that distinction stated in full.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LstmShape {
    /// Two layers, hidden_size 32.
    Standard,
    /// One layer, hidden_size 16.
    Small,
    /// One layer, hidden_size 4 — small enough to keep parity-test signals short and fast.
    Tiny,
}

struct LstmShapeParams {
    hidden_size: usize,
    num_layers: usize,
}

impl LstmShape {
    fn params(self) -> LstmShapeParams {
        match self {
            LstmShape::Standard => LstmShapeParams {
                hidden_size: 32,
                num_layers: 2,
            },
            LstmShape::Small => LstmShapeParams {
                hidden_size: 16,
                num_layers: 1,
            },
            LstmShape::Tiny => LstmShapeParams {
                hidden_size: 4,
                num_layers: 1,
            },
        }
    }

    fn name(self) -> &'static str {
        match self {
            LstmShape::Standard => "standard",
            LstmShape::Small => "small",
            LstmShape::Tiny => "tiny",
        }
    }

    /// This shape's `LstmConfig`: always `input_size == in_channels == out_channels == 1`
    /// (`namir-nam`'s scope restriction — see that crate's `lstm.rs`).
    fn config(self) -> LstmConfig {
        let p = self.params();
        LstmConfig {
            num_layers: p.num_layers,
            input_size: 1,
            hidden_size: p.hidden_size,
            in_channels: 1,
            out_channels: 1,
        }
    }
}

/// Returned by `generate` when calibration cannot produce a finite, sane-RMS fixture (D-19.1's
/// hazard); see this module's doc comment.
#[derive(Debug)]
pub struct DegenerateFixtureError {
    measured_rms: f32,
}

impl fmt::Display for DegenerateFixtureError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "generated fixture is degenerate (output RMS = {}): near-silent or divergent, per \
             D-19.1's explicit hazard — try a different seed",
            self.measured_rms
        )
    }
}
impl Error for DegenerateFixtureError {}

const SAMPLE_RATE: u32 = 48_000;

/// Builds the flat weight array in the order `infer::run` (and any real `.nam` reader) consumes
/// it: per array `[rechannel(w, no bias), per-layer[dilated(w,b), mixin(w), residual(w,b)],
/// head_rechannel(w[, b])]`, then a trailing `head_scale` float.
///
/// Constrained init (D-19.1's accepted fallback to training against an analytic nonlinearity):
/// every weight is uniform over `[-s, s]` with `s = 1/sqrt(fan_in)`, the standard variance-
/// preserving scale — the same reasoning a default PyTorch `Conv1d` init uses. This is what keeps
/// activations from blowing up or collapsing layer over layer purely from initialisation, before
/// the RMS calibration pass even runs. Biases start at zero.
fn build_weights(specs: &[LayerArrayConfig], rng: &mut impl Rng, head_scale: f32) -> Vec<f32> {
    let mut w = Vec::new();
    let push_uniform =
        |rng: &mut dyn rand::RngCore, out: &mut Vec<f32>, count: usize, scale: f32| {
            for _ in 0..count {
                out.push(rng.gen_range(-scale..scale));
            }
        };
    let push_zeros = |out: &mut Vec<f32>, count: usize| out.resize(out.len() + count, 0.0);

    for spec in specs {
        let s = 1.0 / (spec.input_size as f32).sqrt();
        push_uniform(rng, &mut w, spec.channels * spec.input_size, s);

        for _ in &spec.dilations {
            let s = 1.0 / ((spec.channels * spec.kernel_size) as f32).sqrt();
            push_uniform(
                rng,
                &mut w,
                spec.channels * spec.channels * spec.kernel_size,
                s,
            );
            push_zeros(&mut w, spec.channels);

            let s = 1.0 / (spec.condition_size as f32).sqrt();
            push_uniform(rng, &mut w, spec.channels * spec.condition_size, s);

            let s = 1.0 / (spec.channels as f32).sqrt();
            push_uniform(rng, &mut w, spec.channels * spec.channels, s);
            push_zeros(&mut w, spec.channels);
        }

        let s = 1.0 / (spec.channels as f32).sqrt();
        push_uniform(rng, &mut w, spec.head_size * spec.channels, s);
        if spec.head_bias {
            push_zeros(&mut w, spec.head_size);
        }
    }
    w.push(head_scale);
    w
}

/// A short, seeded calibration probe: a low tone plus a little noise, comparable in spirit to
/// the S-1 spike's, just shorter (this crate's `run` is unoptimized/whole-signal, so keeping the
/// probe short matters for test speed — a few thousand samples is already a stable RMS estimate).
fn calibration_probe(seed: u64) -> Vec<f32> {
    let mut rng = rand_pcg::Pcg64::seed_from_u64(seed ^ 0xC411_B4A7);
    let n = 8_000;
    (0..n)
        .map(|i| {
            let t = i as f32 / SAMPLE_RATE as f32;
            0.3 * crate::detmath::sin_f32(2.0 * std::f32::consts::PI * 220.0 * t)
                + 0.05 * rng.gen_range(-1.0f32..1.0)
        })
        .collect()
}

fn measure_output_rms(model: &NamModel, probe: &[f32]) -> f32 {
    let out = infer::run(model, probe);
    let sum_sq: f64 = out.iter().map(|&v| (v as f64) * (v as f64)).sum();
    ((sum_sq / out.len() as f64).sqrt()) as f32
}

fn build_model(shape: WaveNetShape, weights: Vec<f32>, head_scale: f32) -> NamModel {
    let layers = shape.layer_configs();
    NamModel {
        version: "0.5.5".to_string(),
        architecture: "WaveNet".to_string(),
        config: WaveNetConfig {
            layers,
            head_scale,
            head: None,
        },
        weights,
        sample_rate: SAMPLE_RATE,
        metadata: NamMetadata {
            name: format!("namir-fixtures generated {} WaveNet", shape.name()),
            modeled_by: "namir-fixtures".to_string(),
            gear_type: "amp".to_string(),
            tone_type: "clean".to_string(),
            description: "Seeded, constrained-init WaveNet (D-19.1): not trained, tonal realism \
                is irrelevant, only architecture and weights matter for a parity test."
                .to_string(),
        },
    }
}

/// Generates a deterministic, RMS-calibrated `.nam` WaveNet fixture: same `(shape, seed)` always
/// produces byte-identical weights and output — **on every platform, not merely on every run of
/// one machine**.
///
/// That distinction is the whole reason [`crate::detmath`] exists, and it was not always true:
/// the calibration pass below runs a full inference, so until this generator stopped calling the
/// platform libm, one differing `tanh` or `sin` anywhere in it moved `head_scale` (and the
/// trailing weight mirroring it) by a ULP, and CI regenerated the checked-in goldens into
/// different bytes than the machine that wrote them. Everything else here was already exact:
/// `rand_pcg`'s bits, IEEE arithmetic, and `ryu`'s float printing.
/// [`tests::calibration_is_reproducible_across_platforms_to_the_bit`] pins the calibrated value
/// for every shape a checked-in fixture is generated from, so a platform that disagrees fails
/// here rather than silently writing a different golden.
///
/// Two passes: build weights with constrained init and a placeholder `head_scale`, measure the
/// resulting output RMS over a calibration probe, then rescale `head_scale` so the *calibrated*
/// output lands at a fixed target RMS. Returns [`DegenerateFixtureError`] if calibration still
/// can't produce a finite, sane RMS (D-19.1's hazard) — the caller should try a different seed.
pub fn generate(shape: WaveNetShape, seed: u64) -> Result<NamModel, DegenerateFixtureError> {
    let specs = shape.layer_configs();
    let base_head_scale = BASE_HEAD_SCALE;

    let mut rng = rand_pcg::Pcg64::seed_from_u64(seed);
    let weights = build_weights(&specs, &mut rng, base_head_scale);
    let model = build_model(shape, weights, base_head_scale);

    let probe = calibration_probe(seed);
    let measured_rms = measure_output_rms(&model, &probe);
    if !measured_rms.is_finite() || measured_rms <= 1e-6 {
        return Err(DegenerateFixtureError { measured_rms });
    }

    let target_rms = 0.15f32;
    let calibrated_head_scale = base_head_scale * (target_rms / measured_rms);
    let mut weights = model.weights;
    *weights.last_mut().expect("head_scale weight present") = calibrated_head_scale;
    let model = build_model(shape, weights, calibrated_head_scale);

    let calibrated_rms = measure_output_rms(&model, &probe);
    if !calibrated_rms.is_finite() || calibrated_rms <= 1e-4 || calibrated_rms >= 10.0 {
        return Err(DegenerateFixtureError {
            measured_rms: calibrated_rms,
        });
    }

    Ok(model)
}

/// D-19.1's fixture for NFR-PERF-050's 50 MB worst-case load-time figure.
///
/// **Deliberately not RMS-calibrated**, unlike [`generate`]'s real architecture shapes:
/// NFR-PERF-050 is entirely about parse/allocate time, this fixture is never processed through
/// `Stage::process` or judged on tone, and running `generate`'s two calibration inference passes
/// over a network with millions of parameters would make generating this fixture itself
/// impractically slow — the whole reason this is a separate function rather than a fifth
/// [`WaveNetShape`] variant reusing [`generate`]. Weights are the same fan-in-scaled constrained
/// init [`build_weights`] always uses (so the file is at least a structurally plausible WaveNet,
/// not garbage bytes padded to size), just never measured or rescaled.
///
/// **Honest caveat, worth repeating wherever this fixture is used:** a 50 MB `.nam` file is not a
/// shape the NAM ecosystem actually produces — a real exported model runs from a few hundred KB to
/// a few MB. This exists purely to give NFR-PERF-050's stated ceiling a concrete file to measure
/// against, not because it represents anything a user will ever load.
///
/// `channels` is exposed rather than a target byte count so this function stays a pure,
/// deterministic generator with no internal search loop; a caller wanting a specific file size
/// (`benches/resource_load.rs`) picks a `channels` value once, empirically, and pins the result
/// with its own test.
pub fn generate_oversized_uncalibrated(channels: usize, seed: u64) -> NamModel {
    let specs = vec![LayerArrayConfig {
        input_size: 1,
        condition_size: 1,
        head_size: 1,
        channels,
        kernel_size: 3,
        dilations: vec![1, 2, 4, 8],
        activation: "Tanh".to_string(),
        gated: false,
        head_bias: true,
    }];
    let mut rng = rand_pcg::Pcg64::seed_from_u64(seed);
    let head_scale = 0.02f32;
    let weights = build_weights(&specs, &mut rng, head_scale);
    NamModel {
        version: "0.5.5".to_string(),
        architecture: "WaveNet".to_string(),
        config: WaveNetConfig {
            layers: specs,
            head_scale,
            head: None,
        },
        weights,
        sample_rate: SAMPLE_RATE,
        metadata: NamMetadata {
            name: format!("namir-fixtures oversized ({channels}-channel) WaveNet"),
            modeled_by: "namir-fixtures".to_string(),
            gear_type: "amp".to_string(),
            tone_type: "clean".to_string(),
            description: "Uncalibrated load-time fixture (D-19.1/NFR-PERF-050): not RMS-\
                calibrated, not a shape the NAM ecosystem produces, exists only to measure \
                parse/allocate time at a stated worst-case file size."
                .to_string(),
        },
    }
}

// === A2 (`crates/namir-fixtures`'s independent A2 fixture generator, M10) =====================
//
// Ground truth for everything below: `NeuralAmpModelerCore` pinned at `3cde95c`
// (`C:\namref`), specifically `NAM/wavenet/model.cpp`, `NAM/conv1d.cpp`, `NAM/dsp.cpp`,
// `NAM/wavenet/detail.h` and `NAM/wavenet/a2_fast.h`/`a2_fast.cpp`. This section is written
// independently of `crates/namir-nam`'s own A2 work (R-9, `docs/02-architecture.md` §22) — see
// this module's own doc comment and the milestone task that produced it for why that independence
// matters; nothing below was read from or cross-checked against `namir-nam`.

/// One layer's activation config inside an A2 layer array's `activation` array — this crate's
/// mirror of the real `.nam` schema's per-layer activation object (`a2_fast.cpp`'s detector,
/// `is_a2_shape`, ~825-835: `{"type": "LeakyReLU", "negative_slope": <f32>}`). Core A2 always uses
/// `negative_slope: 0.01` (`a2_fast.h`'s `kLeakySlope`), but the field is a real JSON knob —
/// `activations.cpp` confirms every activation parameter comes from config, never the weight
/// stream — so it's carried here rather than hard-coded past the generator boundary.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct A2ActivationConfig {
    /// Always `"LeakyReLU"` for fixtures generated by this module.
    #[serde(rename = "type")]
    pub kind: String,
    /// LeakyReLU's negative-slope coefficient; `0.01` for real "A2 standard"/"A2 nano" models.
    pub negative_slope: f32,
}

/// An A2 layer array's `layer1x1` sub-config — present and `active` on every layer of every
/// core-A2 shape (`a2_fast.cpp`'s detector requires it: ~866-873). `namir-fixtures` never emits
/// `head1x1`, `condition_dsp`, `gating_mode`, or `slimmable` fields at all (out of this module's
/// scope): omitting a mirror type for each of those leaves the field entirely absent from the
/// serialized JSON, which is exactly what the strict A2 detector requires for those particular
/// fields (`is_a2_shape`, `a2_fast.cpp:758-909` — each is only rejected when *present* and
/// non-trivial, so a config that never emits it still matches).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct A2Layer1x1Config {
    /// Always `true` for fixtures generated by this module — `layer1x1` inactive is a different,
    /// non-A2 WaveNet shape this crate does not generate (and would require `bottleneck ==
    /// channels`, `detail.h:60-65`).
    pub active: bool,
    /// Always `1` — core A2 never groups this convolution.
    pub groups: usize,
}

/// An A2 layer array's nested `head` sub-config: a genuine k-tap, dilated causal `Conv1D` (unlike
/// [`LayerArrayConfig`]'s implicit 1x1 head rechannel), matching `LayerArray`'s `_head_rechannel`
/// member (`detail.h:350-351`) and its construction (`model.cpp:380-384`: built directly from
/// `head_size`/`head_kernel_size`/`head_bias`/`head_dilation`, with its input width —
/// `_head_output_size` — equal to `bottleneck` since core A2 never activates `head1x1`).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct A2HeadRechannelConfig {
    /// Output channel count; `1` for both real A2 shapes (the detector requires exactly this).
    pub out_channels: usize,
    /// Convolution kernel width; `16` for both real A2 shapes (`kHeadKernelSize`, `a2_fast.h:33`).
    pub kernel_size: usize,
    /// Dilation factor; `1` for both real A2 shapes.
    pub head_dilation: usize,
    /// Whether this convolution applies a bias term; always `true` for fixtures generated by this
    /// module (matches both real A2 shapes — the detector requires it: `a2_fast.cpp:885`).
    pub bias: bool,
}

/// One A2 layer array's hyperparameters — the A2 analogue of [`LayerArrayConfig`], structurally
/// different rather than a superset: A2 has a per-layer `kernel_sizes`/`dilations` pair (not one
/// shared `kernel_size`), an internal `bottleneck` width distinct from `channels` (`detail.h`'s
/// `Layer` constructor, ~44-53), a per-layer `activation` array rather than one shared activation
/// name, an explicit `layer1x1` sub-config, and a real convolutional nested `head` rather than an
/// implicit 1x1. Field names mirror the real `.nam` A2 schema as read by `is_a2_shape`
/// (`a2_fast.cpp:758-909`).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct A2LayerArrayConfig {
    /// Number of input channels into this layer array; always `1` (raw mono signal) for fixtures
    /// generated by this module.
    pub input_size: usize,
    /// Number of conditioning channels; always `1`, and always fed the model's original raw
    /// input at every layer (see [`a2_infer::run`]'s doc comment on the two-signal handoff — same
    /// convention `infer.rs` already documents for A1, confirmed unchanged for A2 by
    /// `WaveNet::process`, `model.cpp:744-772`).
    pub condition_size: usize,
    /// Number of channels each layer's residual trunk carries (the `layer1x1` output width and
    /// the array's `_rechannel` output width).
    pub channels: usize,
    /// Number of channels the dilated conv / input mixin / activation operate at internally, per
    /// layer (`Layer`'s `_bottleneck`, `detail.h:45-53`). Equal to `channels` for both real A2
    /// shapes (the detector requires it: `a2_fast.cpp:798-803`) but deliberately *not* equal for
    /// [`A2Shape::BottleneckProbe`] — see that variant's doc comment.
    pub bottleneck: usize,
    /// Per-layer convolution kernel widths, one entry per layer.
    pub kernel_sizes: Vec<usize>,
    /// Per-layer dilation factors, one entry per layer.
    pub dilations: Vec<usize>,
    /// Per-layer activation config, one entry per layer; fixtures generated by this module always
    /// use `LeakyReLU`.
    pub activation: Vec<A2ActivationConfig>,
    /// The post-activation projection back to `channels` width feeding the residual connection
    /// (`detail.h`'s `_layer1x1`); always active for fixtures generated by this module.
    pub layer1x1: A2Layer1x1Config,
    /// The layer array's own dilated-conv head rechannel, applied once after all layers'
    /// activated outputs are summed.
    pub head: A2HeadRechannelConfig,
}

/// An A2 model's top-level configuration — the same shape as [`WaveNetConfig`] (`layers` +
/// `head_scale` + a `head` field that's always `null`/absent for both), just parameterized over
/// [`A2LayerArrayConfig`] instead of [`LayerArrayConfig`]. `namir-fixtures` only ever generates a
/// single layer array (core A2's own constraint — `a2_fast.cpp:760-763` rejects anything else), so
/// `layers` always has length 1, but the field stays a `Vec` — same reasoning as
/// [`WaveNetConfig::layers`] — rather than a single struct, so [`a2_infer::run`]'s array-chaining
/// loop isn't a special case for the one array it's ever actually given.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct A2WaveNetConfig {
    /// The model's layer-array stack, in evaluation order; always length 1 for fixtures generated
    /// by this module.
    pub layers: Vec<A2LayerArrayConfig>,
    /// Output scaling applied after the (nested, per-array) head; the value `generate_a2`'s
    /// calibration pass rescales.
    pub head_scale: f32,
    /// The model's *top-level*, post-stack head (`WaveNet::_post_stack_head`) — distinct from
    /// each layer array's own nested `head` above. Always `None`/absent: `is_a2_shape` requires
    /// this be null (`a2_fast.cpp:766-768`).
    pub head: Option<serde_json::Value>,
}

/// A generated `.nam` A2 fixture: the A2 analogue of [`NamModel`]. `architecture` stays
/// `"WaveNet"` — A2 is not a separate top-level architecture, it's a WaveNet whose `config` shape
/// the strict detector `is_a2_shape` recognizes (`a2_fast.h`'s own comment: "the 'config'
/// sub-object from a .nam WaveNet entry").
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct A2Model {
    /// The exporter's format version string this fixture claims.
    pub version: String,
    /// Always `"WaveNet"` — see this struct's doc comment.
    pub architecture: String,
    /// The A2 topology and weights layout.
    pub config: A2WaveNetConfig,
    /// The flat weight vector, laid out per `build_a2_weights`'s doc comment.
    pub weights: Vec<f32>,
    /// The sample rate this fixture declares (always `SAMPLE_RATE`).
    pub sample_rate: u32,
    /// Display-only metadata identifying this as a generated fixture.
    pub metadata: NamMetadata,
}

impl A2Model {
    /// Serializes to pretty-printed `.nam` JSON bytes; see `NamModel::to_json_bytes`.
    pub fn to_json_bytes(&self) -> Vec<u8> {
        serde_json::to_vec_pretty(self).expect("A2Model always serializes")
    }

    /// Parses `.nam` JSON bytes back into an `A2Model`, the inverse of `to_json_bytes`.
    pub fn from_json_bytes(bytes: &[u8]) -> Result<Self, serde_json::Error> {
        serde_json::from_slice(bytes)
    }
}

/// The three A2 shapes this module can generate.
///
/// **Naming, recorded once, explicitly:** `Full` corresponds to upstream's "A2 standard"
/// (`channels == bottleneck == 8`) and `Lite` to upstream's "A2 nano" (`channels == bottleneck ==
/// 3`). Source: `a2_fast.h`'s own header comment ("the A2 standard (Channels=8) and A2 nano
/// (Channels=3) models") and `a2_fast.cpp`'s `is_a2_shape` detector (~798-803: `channels != 3 &&
/// channels != 8` is rejected outright). The FRS's "A2-Full"/"A2-Lite" names do not appear
/// anywhere in the upstream C++ source — this mapping is not recorded anywhere else in this repo,
/// so it's stated here, at the one place this crate needs it, rather than assumed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum A2Shape {
    /// Upstream's "A2 standard": `channels == bottleneck == 8`, 23 layers, single layer array.
    Full,
    /// Upstream's "A2 nano": `channels == bottleneck == 3`, 23 layers, single layer array.
    Lite,
    /// **Not an upstream shape — this crate's own invention, for coverage only.** Both real A2
    /// shapes require `bottleneck == channels` (`a2_fast.cpp:798-803`'s detector rejects anything
    /// else), so without a third shape, no generated fixture would ever exercise `namir-nam`'s
    /// `bottleneck != channels` code path at all. A small, 3-layer, single-array topology with
    /// `channels = 6`, `bottleneck = 3`, and (for the same reason) a dilated rather than trivial
    /// head (`head_dilation = 2`), deliberately *not* shaped to pass `is_a2_shape`.
    BottleneckProbe,
}

fn a2_leaky_relu_config() -> A2ActivationConfig {
    A2ActivationConfig {
        kind: "LeakyReLU".to_string(),
        negative_slope: 0.01,
    }
}

/// Builds the exact core-A2 layer array topology (`a2_fast.h`'s `kKernelSizes`/`kDilations`,
/// `kLeakySlope`, `kHeadKernelSize`) for a given channel count (8 for "A2 standard"/[`A2Shape::Full`],
/// 3 for "A2 nano"/[`A2Shape::Lite`]) — not a simplification: this is the real 23-layer,
/// single-array topology the strict detector requires, reproduced exactly rather than invented.
fn a2_core_layer_array(channels: usize) -> Vec<A2LayerArrayConfig> {
    // a2_fast.h:38-39.
    const KERNEL_SIZES: [usize; 23] = [
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 15, 15, 6, 6, 6, 6, 6, 6, 6,
    ];
    // a2_fast.h:42-43.
    const DILATIONS: [usize; 23] = [
        1, 3, 7, 17, 41, 101, 239, 1, 3, 7, 17, 41, 101, 239, 1, 13, 1, 3, 7, 17, 41, 101, 239,
    ];
    vec![A2LayerArrayConfig {
        input_size: 1,
        condition_size: 1,
        channels,
        bottleneck: channels,
        kernel_sizes: KERNEL_SIZES.to_vec(),
        dilations: DILATIONS.to_vec(),
        activation: (0..KERNEL_SIZES.len())
            .map(|_| a2_leaky_relu_config())
            .collect(),
        layer1x1: A2Layer1x1Config {
            active: true,
            groups: 1,
        },
        head: A2HeadRechannelConfig {
            out_channels: 1,
            kernel_size: 16,
            head_dilation: 1,
            bias: true,
        },
    }]
}

impl A2Shape {
    fn name(self) -> &'static str {
        match self {
            A2Shape::Full => "a2-full",
            A2Shape::Lite => "a2-lite",
            A2Shape::BottleneckProbe => "a2-bottleneck-probe",
        }
    }

    /// The single `A2LayerArrayConfig` for this shape, in evaluation order (always length 1 —
    /// see [`A2WaveNetConfig::layers`]'s doc comment for why the type stays a `Vec` regardless).
    fn layer_configs(self) -> Vec<A2LayerArrayConfig> {
        match self {
            A2Shape::Full => a2_core_layer_array(8),
            A2Shape::Lite => a2_core_layer_array(3),
            A2Shape::BottleneckProbe => vec![A2LayerArrayConfig {
                input_size: 1,
                condition_size: 1,
                channels: 6,
                bottleneck: 3,
                kernel_sizes: vec![3, 3, 5],
                dilations: vec![1, 2, 4],
                activation: (0..3).map(|_| a2_leaky_relu_config()).collect(),
                layer1x1: A2Layer1x1Config {
                    active: true,
                    groups: 1,
                },
                head: A2HeadRechannelConfig {
                    out_channels: 1,
                    kernel_size: 4,
                    head_dilation: 2,
                    bias: true,
                },
            }],
        }
    }
}

/// Builds the flat weight array in the order `a2_infer::run` (and any real A2-shape `.nam`
/// reader) consumes it, derived directly from the upstream weight-consumption walk and
/// cross-checked against `a2_fast.cpp`'s own independent restatement of the same order
/// (`A2FastModel::_load_weights`, ~186-266 — its doc comment there states the identical order
/// this comment derives independently from `model.cpp`/`conv1d.cpp`/`dsp.cpp`).
///
/// `WaveNet::set_weights_` (`model.cpp:623-645`) reads, per layer array, `LayerArray::set_weights_`
/// (`model.cpp:525-531`): `_rechannel`, then each layer's `Layer::set_weights_`
/// (`model.cpp:135-164`) in turn, then `_head_rechannel`. Per layer (`Layer::set_weights_`'s
/// literal call order, matching its constructor's module order in `detail.h:44-53`): `_conv`
/// (dilated), `_input_mixin`, `_layer1x1` — `_head1x1` and every FiLM module are skipped, since
/// core A2 never activates them. After every layer array, a single trailing `head_scale` float is
/// read (`model.cpp:632`) — confirmed still present for A2: `WaveNet::set_weights_` reads it
/// unconditionally after the layer-array loop and the (absent, for A2) `_post_stack_head`, with no
/// architecture-specific branch, and `A2FastModel::_load_weights` reads the same trailing float
/// itself (`a2_fast.cpp:268-269`, "Matches `WaveNet::set_weights_`: the last value in the stream is
/// `head_scale`").
///
/// Each module's own weight order (`Conv1D::set_weights_`, `conv1d.cpp:10-54`;
/// `Conv1x1::set_weights_`, `dsp.cpp:363-398`): for each group (always 1 here), for each output
/// channel, for each input channel, for each kernel tap (tap innermost) — i.e. row-major
/// `[out][in][k]`, matching PyTorch's native `Conv1d.weight` flatten — then the module's bias
/// vector, if it has one. So, per layer array:
///
/// ```text
/// rechannel_w                     (channels * input_size; no bias)
/// for each layer:
///   dilated_conv_w, dilated_conv_b  (bottleneck * channels * kernel_size, then bottleneck)
///   mixin_w                         (bottleneck * condition_size; no bias)
///   layer1x1_w, layer1x1_b          (channels * bottleneck, then channels)
/// head_rechannel_w, head_rechannel_b
///                                  (head.out_channels * bottleneck * head.kernel_size,
///                                   then head.out_channels)
/// ```
/// ...then, after every layer array, a trailing `head_scale` float.
///
/// Constrained init, same reasoning as `build_weights`: every weight is uniform over `[-s, s]`
/// with `s = 1/sqrt(fan_in)`, the standard variance-preserving scale. Biases start at zero.
fn build_a2_weights(specs: &[A2LayerArrayConfig], rng: &mut impl Rng, head_scale: f32) -> Vec<f32> {
    let mut w = Vec::new();
    let push_uniform =
        |rng: &mut dyn rand::RngCore, out: &mut Vec<f32>, count: usize, scale: f32| {
            for _ in 0..count {
                out.push(rng.gen_range(-scale..scale));
            }
        };
    let push_zeros = |out: &mut Vec<f32>, count: usize| out.resize(out.len() + count, 0.0);

    for spec in specs {
        let s = 1.0 / (spec.input_size as f32).sqrt();
        push_uniform(rng, &mut w, spec.channels * spec.input_size, s);

        for &kernel_size in &spec.kernel_sizes {
            let s = 1.0 / ((spec.channels * kernel_size) as f32).sqrt();
            push_uniform(
                rng,
                &mut w,
                spec.bottleneck * spec.channels * kernel_size,
                s,
            );
            push_zeros(&mut w, spec.bottleneck);

            let s = 1.0 / (spec.condition_size as f32).sqrt();
            push_uniform(rng, &mut w, spec.bottleneck * spec.condition_size, s);

            let s = 1.0 / (spec.bottleneck as f32).sqrt();
            push_uniform(rng, &mut w, spec.channels * spec.bottleneck, s);
            push_zeros(&mut w, spec.channels);
        }

        let s = 1.0 / ((spec.bottleneck * spec.head.kernel_size) as f32).sqrt();
        push_uniform(
            rng,
            &mut w,
            spec.head.out_channels * spec.bottleneck * spec.head.kernel_size,
            s,
        );
        if spec.head.bias {
            push_zeros(&mut w, spec.head.out_channels);
        }
    }
    w.push(head_scale);
    w
}

fn measure_a2_output_rms(model: &A2Model, probe: &[f32]) -> f32 {
    let out = a2_infer::run(model, probe);
    let sum_sq: f64 = out.iter().map(|&v| (v as f64) * (v as f64)).sum();
    ((sum_sq / out.len() as f64).sqrt()) as f32
}

fn build_a2_model(shape: A2Shape, weights: Vec<f32>, head_scale: f32) -> A2Model {
    let layers = shape.layer_configs();
    A2Model {
        version: "0.5.5".to_string(),
        architecture: "WaveNet".to_string(),
        config: A2WaveNetConfig {
            layers,
            head_scale,
            head: None,
        },
        weights,
        sample_rate: SAMPLE_RATE,
        metadata: NamMetadata {
            name: format!("namir-fixtures generated {} WaveNet (A2)", shape.name()),
            modeled_by: "namir-fixtures".to_string(),
            gear_type: "amp".to_string(),
            tone_type: "clean".to_string(),
            description: "Seeded, constrained-init A2 WaveNet (D-19.1): not trained, tonal \
                realism is irrelevant, only architecture and weights matter for a parity test."
                .to_string(),
        },
    }
}

/// Generates a deterministic, RMS-calibrated `.nam` A2 fixture: same `(shape, seed)` always
/// produces byte-identical weights and output, on every platform. The A2 analogue of
/// [`generate`]; see that function's doc comment for the two-pass calibration shape this follows
/// unchanged, and for the cross-platform claim.
///
/// This is the shape that *demonstrated* the problem [`crate::detmath`] fixes. A2 inference is
/// LeakyReLU throughout — pure arithmetic, no libm — so the only transcendental anywhere in this
/// function was [`calibration_probe`]'s `sin`, and that alone was enough for M14's CI to
/// regenerate `a2_full.nam` with a different `head_scale` on all three runners. The committed
/// bytes now come back identical here; `namir-nam`'s `the_a2_golden_models_match_their_generator`
/// still compares that one value under a relative tolerance rather than byte for byte, which is
/// no longer necessary but is harmless.
pub fn generate_a2(shape: A2Shape, seed: u64) -> Result<A2Model, DegenerateFixtureError> {
    let specs = shape.layer_configs();
    let base_head_scale = 0.02f32;

    let mut rng = rand_pcg::Pcg64::seed_from_u64(seed);
    let weights = build_a2_weights(&specs, &mut rng, base_head_scale);
    let model = build_a2_model(shape, weights, base_head_scale);

    let probe = calibration_probe(seed);
    let measured_rms = measure_a2_output_rms(&model, &probe);
    if !measured_rms.is_finite() || measured_rms <= 1e-6 {
        return Err(DegenerateFixtureError { measured_rms });
    }

    let target_rms = 0.15f32;
    let calibrated_head_scale = base_head_scale * (target_rms / measured_rms);
    let mut weights = model.weights;
    *weights.last_mut().expect("head_scale weight present") = calibrated_head_scale;
    let model = build_a2_model(shape, weights, calibrated_head_scale);

    let calibrated_rms = measure_a2_output_rms(&model, &probe);
    if !calibrated_rms.is_finite() || calibrated_rms <= 1e-4 || calibrated_rms >= 10.0 {
        return Err(DegenerateFixtureError {
            measured_rms: calibrated_rms,
        });
    }

    Ok(model)
}

/// Builds the flat weight array in the order `lstm_infer::run` (and `namir-nam`'s `lstm.rs`)
/// consume it: per layer `[W, b, h0, c0]` (layer 0's `W` has `cell_input_size == input_size`,
/// every later layer's has `cell_input_size == hidden_size`), then `head_weight`, `head_bias` —
/// no trailing scalar, unlike WaveNet's `head_scale`.
///
/// Constrained init, same reasoning as `build_weights`: every `W`/`head_weight` entry is uniform
/// over `[-s, s]` with `s = 1/sqrt(fan_in)`. Biases (`b`, `head_bias`) start at zero. `h0`/`c0`
/// (the *learned* initial hidden/cell state — see `namir-nam`'s `lstm.rs` doc comment) get a
/// small uniform init of their own (`s = 0.1`, not fan-in-scaled): a real export's initial state
/// isn't zero, but there's no fan-in to scale it by either, and it isn't the calibration knob —
/// `generate_lstm`'s calibration pass rescales the head instead, since (unlike gate weights) the
/// head's output is exactly linear in its own weights (see `generate_lstm`'s doc comment).
fn build_lstm_weights(cfg: &LstmConfig, rng: &mut impl Rng) -> Vec<f32> {
    let mut w = Vec::new();
    let push_uniform =
        |rng: &mut dyn rand::RngCore, out: &mut Vec<f32>, count: usize, scale: f32| {
            for _ in 0..count {
                out.push(rng.gen_range(-scale..scale));
            }
        };
    let push_zeros = |out: &mut Vec<f32>, count: usize| out.resize(out.len() + count, 0.0);

    for i in 0..cfg.num_layers {
        let cell_input_size = if i == 0 {
            cfg.input_size
        } else {
            cfg.hidden_size
        };
        let rows = 4 * cfg.hidden_size;
        let cols = cell_input_size + cfg.hidden_size;
        let s = 1.0 / (cols as f32).sqrt();
        push_uniform(rng, &mut w, rows * cols, s); // W
        push_zeros(&mut w, rows); // b
        push_uniform(rng, &mut w, cfg.hidden_size, 0.1); // h0
        push_uniform(rng, &mut w, cfg.hidden_size, 0.1); // c0
    }

    let s = 1.0 / (cfg.hidden_size as f32).sqrt();
    push_uniform(rng, &mut w, cfg.out_channels * cfg.hidden_size, s); // head_weight
    push_zeros(&mut w, cfg.out_channels); // head_bias
    w
}

fn measure_lstm_output_rms(model: &LstmModel, probe: &[f32]) -> f32 {
    let out = lstm_infer::run(model, probe);
    let sum_sq: f64 = out.iter().map(|&v| (v as f64) * (v as f64)).sum();
    ((sum_sq / out.len() as f64).sqrt()) as f32
}

fn build_lstm_model(shape: LstmShape, weights: Vec<f32>) -> LstmModel {
    LstmModel {
        version: "0.5.5".to_string(),
        architecture: "LSTM".to_string(),
        config: shape.config(),
        weights,
        sample_rate: SAMPLE_RATE,
        metadata: NamMetadata {
            name: format!("namir-fixtures generated {} LSTM", shape.name()),
            modeled_by: "namir-fixtures".to_string(),
            gear_type: "amp".to_string(),
            tone_type: "clean".to_string(),
            description: "Seeded, constrained-init LSTM (D-19.1): not trained, tonal realism is \
                irrelevant, only architecture and weights matter for a parity test."
                .to_string(),
        },
    }
}

/// Generates a deterministic, RMS-calibrated `.nam` LSTM fixture: same `(shape, seed)` always
/// produces byte-identical weights and output, on every platform — the LSTM counterpart of
/// [`generate`]; see that function's doc comment for the two-pass shape this follows and for what
/// "on every platform" cost. This architecture reaches the platform libm twice over (`tanh` *and*
/// the sigmoid's `exp`), and its calibration scales the whole head tail rather than one float, so
/// a libm difference used to land in several weights rather than one.
///
/// The one structural difference from `generate`: WaveNet has a single trailing `head_scale`
/// float to rescale for calibration; LSTM has no such scalar (see `build_lstm_weights`'s doc
/// comment), so this rescales the flat weight array's *tail* — `head_weight` and `head_bias`
/// together, the last `out_channels * hidden_size + out_channels` floats — by a factor `k`
/// instead. That is exactly equivalent to WaveNet's single-float rescale, not an approximation:
/// the head is the last stage applied (`output = head_weight @ h_last + head_bias`) and nothing
/// upstream of it (the layer stack, `h_last` itself) depends on the head's own weights, so
/// scaling both `head_weight` and `head_bias` by `k` scales `output` by exactly `k`.
pub fn generate_lstm(shape: LstmShape, seed: u64) -> Result<LstmModel, DegenerateFixtureError> {
    let cfg = shape.config();

    let mut rng = rand_pcg::Pcg64::seed_from_u64(seed);
    let weights = build_lstm_weights(&cfg, &mut rng);
    let model = build_lstm_model(shape, weights);

    let probe = calibration_probe(seed);
    let measured_rms = measure_lstm_output_rms(&model, &probe);
    if !measured_rms.is_finite() || measured_rms <= 1e-6 {
        return Err(DegenerateFixtureError { measured_rms });
    }

    let target_rms = 0.15f32;
    let k = target_rms / measured_rms;
    let head_len = cfg.out_channels * cfg.hidden_size + cfg.out_channels;
    let mut weights = model.weights;
    let tail_start = weights
        .len()
        .checked_sub(head_len)
        .expect("weights always at least as long as the head, by construction");
    for w in &mut weights[tail_start..] {
        *w *= k;
    }
    let model = build_lstm_model(shape, weights);

    let calibrated_rms = measure_lstm_output_rms(&model, &probe);
    if !calibrated_rms.is_finite() || calibrated_rms <= 1e-4 || calibrated_rms >= 10.0 {
        return Err(DegenerateFixtureError {
            measured_rms: calibrated_rms,
        });
    }

    Ok(model)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_without_error_for_all_shapes() {
        for shape in [
            WaveNetShape::Standard,
            WaveNetShape::Lite,
            WaveNetShape::Feather,
            WaveNetShape::Nano,
        ] {
            generate(shape, 1).unwrap_or_else(|e| panic!("{shape:?}: {e}"));
        }
    }

    /// Determinism *across machines*, not just within one run — the property "same `(shape, seed)`
    /// gives byte-identical weights" claims and [`generation_is_deterministic_for_a_given_seed`]
    /// cannot check, because a second call on the same machine reproduces that machine's own libm
    /// exactly.
    ///
    /// Until [`crate::detmath`] landed, the claim was false: `head_scale` is calibrated through a
    /// full inference pass, so one differing `tanh`/`sin`/`exp` anywhere in it moved that float,
    /// and M14 watched exactly that happen — the checked-in A2 goldens regenerated to
    /// `head_scale: 0.15790401` on all three CI runners and `0.15790403` on the machine that wrote
    /// them. These pins are the tripwire that failure needed: the calibrated value for each shape
    /// a checked-in fixture is generated from, to the bit. Nothing about the numbers themselves is
    /// significant — what matters is that every platform agrees on them, so a machine that
    /// disagrees fails *here*, at the generator, naming the cause, instead of silently writing a
    /// different golden or corpus file.
    ///
    /// If one of these ever fails, do not adjust the constant. The generator has either changed
    /// (then the paired committed fixtures and their externally-rendered references must be
    /// regenerated together — see `namir-nam/tests/golden_reference.rs`'s recipe) or something in
    /// the calibration path has stopped being reproducible (then find it: every operation on that
    /// path is required to be IEEE-754-specified arithmetic).
    #[test]
    fn calibration_is_reproducible_across_platforms_to_the_bit() {
        // `wavenet_nano.nam` and `fuzz/corpus/load_nam/valid_nano.json`'s shapes and seeds.
        for (shape, seed, bits) in [
            (WaveNetShape::Nano, 30u64, 0x3f1c_9606u32),
            (WaveNetShape::Nano, 1, 0x3e52_e218),
        ] {
            let model = generate(shape, seed).unwrap_or_else(|e| panic!("{shape:?}/{seed}: {e}"));
            assert_eq!(
                model.config.head_scale.to_bits(),
                bits,
                "{shape:?}/{seed}: calibrated head_scale is {} ({:#010x}), not the value every \
                 platform must agree on",
                model.config.head_scale,
                model.config.head_scale.to_bits()
            );
            assert_eq!(
                model.weights.last().copied().map(f32::to_bits),
                Some(bits),
                "{shape:?}/{seed}: the trailing weight must mirror head_scale exactly"
            );
        }

        // `a2_full.nam` and `a2_lite.nam` — the two shapes whose committed bytes M14's CI could
        // not reproduce.
        for (shape, bits) in [
            (A2Shape::Full, 0x3e21_b198u32),
            (A2Shape::Lite, 0x3f55_7617),
        ] {
            let model = generate_a2(shape, 30).unwrap_or_else(|e| panic!("{shape:?}: {e}"));
            assert_eq!(
                model.config.head_scale.to_bits(),
                bits,
                "{shape:?}: calibrated head_scale is {} ({:#010x}), not the value every platform \
                 must agree on",
                model.config.head_scale,
                model.config.head_scale.to_bits()
            );
        }

        // LSTM calibrates by scaling the head tail rather than a single `head_scale` float, so the
        // pin is on that tail. `lstm_tiny.nam`'s shape and seed.
        let lstm = generate_lstm(LstmShape::Tiny, 30).expect("lstm tiny generates");
        let tail: Vec<u32> = lstm.weights[lstm.weights.len() - 3..]
            .iter()
            .map(|w| w.to_bits())
            .collect();
        assert_eq!(
            tail,
            vec![0x416b_ca35, 0xc186_f4ec, 0x0000_0000],
            "LSTM head tail is {:?}, not the values every platform must agree on",
            &lstm.weights[lstm.weights.len() - 3..]
        );
    }

    #[test]
    fn generation_is_deterministic_for_a_given_seed() {
        let a = generate(WaveNetShape::Standard, 42).unwrap();
        let b = generate(WaveNetShape::Standard, 42).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn different_seeds_produce_different_weights() {
        let a = generate(WaveNetShape::Standard, 1).unwrap();
        let b = generate(WaveNetShape::Standard, 2).unwrap();
        assert_ne!(a.weights, b.weights);
    }

    /// Pins `generate_oversized_uncalibrated`'s size at the channel count
    /// `benches/resource_load.rs` (namir-worker) actually uses, so a future change to
    /// `build_weights`'s layout or this function's own dilation list is caught here rather than
    /// silently drifting the benchmark away from NFR-PERF-050's stated 50 MB figure. Empirically
    /// chosen (see this crate's own commit history for the probe that found it): 430 channels
    /// currently yields ~49.6 MB.
    #[test]
    fn oversized_fixture_at_430_channels_is_close_to_50mb() {
        let bytes = generate_oversized_uncalibrated(430, 1).to_json_bytes();
        let mb = bytes.len() as f64 / (1024.0 * 1024.0);
        assert!(
            (45.0..55.0).contains(&mb),
            "430-channel oversized fixture is {mb:.1} MB, expected roughly 50 MB -- update the \
             channel count in both this test and namir-worker's benches/resource_load.rs"
        );
    }

    #[test]
    fn oversized_fixture_is_deterministic_and_loadable_as_valid_json() {
        let a = generate_oversized_uncalibrated(16, 7);
        let b = generate_oversized_uncalibrated(16, 7);
        assert_eq!(a, b);
        let bytes = a.to_json_bytes();
        let restored = NamModel::from_json_bytes(&bytes).unwrap();
        assert_eq!(restored, a);
    }

    #[test]
    fn shapes_have_decreasing_channel_counts() {
        let sizes: Vec<usize> = [
            WaveNetShape::Standard,
            WaveNetShape::Lite,
            WaveNetShape::Feather,
            WaveNetShape::Nano,
        ]
        .iter()
        .map(|&s| generate(s, 1).unwrap().weights.len())
        .collect();
        for w in sizes.windows(2) {
            assert!(
                w[0] > w[1],
                "expected strictly decreasing weight counts: {sizes:?}"
            );
        }
    }

    #[test]
    fn model_round_trips_through_json() {
        for shape in [
            WaveNetShape::Standard,
            WaveNetShape::Lite,
            WaveNetShape::Feather,
            WaveNetShape::Nano,
        ] {
            let model = generate(shape, 7).unwrap();
            let bytes = model.to_json_bytes();
            let parsed = NamModel::from_json_bytes(&bytes).expect("round trip parses");
            assert_eq!(model, parsed, "{shape:?} did not round-trip");
        }
    }

    #[test]
    fn generated_models_have_bounded_nondegenerate_rms() {
        // D-19.1's explicit hazard: naive random weights can leave a network near-silent or
        // divergent, making an RMS-relative accuracy metric meaningless. This is the actual
        // point of the generator's constrained-init + calibration design, not incidental.
        let probe = calibration_probe(999);
        for shape in [
            WaveNetShape::Standard,
            WaveNetShape::Lite,
            WaveNetShape::Feather,
            WaveNetShape::Nano,
        ] {
            let model = generate(shape, 999).unwrap();
            let rms = measure_output_rms(&model, &probe);
            assert!(rms.is_finite(), "{shape:?}: non-finite RMS");
            assert!(rms > 1e-4, "{shape:?}: near-silent, RMS = {rms}");
            assert!(rms < 10.0, "{shape:?}: divergent, RMS = {rms}");
        }
    }

    #[test]
    fn layer_array_chaining_invariant_holds() {
        for shape in [
            WaveNetShape::Standard,
            WaveNetShape::Lite,
            WaveNetShape::Feather,
            WaveNetShape::Nano,
        ] {
            let layers = shape.layer_configs();
            for w in layers.windows(2) {
                assert_eq!(
                    w[0].head_size, w[1].channels,
                    "{shape:?}: head_size/channels mismatch"
                );
            }
        }
    }

    const A2_SHAPES: [A2Shape; 3] = [A2Shape::Full, A2Shape::Lite, A2Shape::BottleneckProbe];

    #[test]
    fn generates_a2_without_error_for_all_shapes() {
        for shape in A2_SHAPES {
            generate_a2(shape, 1).unwrap_or_else(|e| panic!("{shape:?}: {e}"));
        }
    }

    #[test]
    fn a2_generation_is_deterministic_for_a_given_seed() {
        let a = generate_a2(A2Shape::Full, 42).unwrap();
        let b = generate_a2(A2Shape::Full, 42).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn a2_different_seeds_produce_different_weights() {
        let a = generate_a2(A2Shape::Full, 1).unwrap();
        let b = generate_a2(A2Shape::Full, 2).unwrap();
        assert_ne!(a.weights, b.weights);
    }

    #[test]
    fn a2_model_round_trips_through_json() {
        for shape in A2_SHAPES {
            let model = generate_a2(shape, 7).unwrap();
            let bytes = model.to_json_bytes();
            let parsed = A2Model::from_json_bytes(&bytes).expect("round trip parses");
            assert_eq!(model, parsed, "{shape:?} did not round-trip");
        }
    }

    #[test]
    fn generated_a2_models_have_bounded_nondegenerate_rms() {
        // Same D-19.1 hazard as generated_models_have_bounded_nondegenerate_rms (A1): naive
        // random weights can leave the network near-silent or divergent.
        let probe = calibration_probe(999);
        for shape in A2_SHAPES {
            let model = generate_a2(shape, 999).unwrap();
            let rms = measure_a2_output_rms(&model, &probe);
            assert!(rms.is_finite(), "{shape:?}: non-finite RMS");
            assert!(rms > 1e-4, "{shape:?}: near-silent, RMS = {rms}");
            assert!(rms < 10.0, "{shape:?}: divergent, RMS = {rms}");
        }
    }

    #[test]
    fn a2_layer_array_config_invariants_hold() {
        for shape in A2_SHAPES {
            let layers = shape.layer_configs();
            assert_eq!(
                layers.len(),
                1,
                "{shape:?}: expected exactly one layer array"
            );
            let cfg = &layers[0];
            assert_eq!(
                cfg.kernel_sizes.len(),
                cfg.dilations.len(),
                "{shape:?}: kernel_sizes/dilations length mismatch"
            );
            assert_eq!(
                cfg.kernel_sizes.len(),
                cfg.activation.len(),
                "{shape:?}: kernel_sizes/activation length mismatch"
            );
            assert!(cfg.layer1x1.active, "{shape:?}: layer1x1 must be active");
            assert!(cfg.head.bias, "{shape:?}: head.bias must be true");
        }
    }

    #[test]
    fn a2_full_and_lite_match_upstream_core_a2_shape() {
        // Pins the mapping this module's own doc comment on `A2Shape` records: `Full` == upstream
        // "A2 standard" (channels/bottleneck 8), `Lite` == upstream "A2 nano" (channels/bottleneck
        // 3), both with bottleneck == channels, 23 layers and a single layer array (`a2_fast.h`/
        // `a2_fast.cpp`'s `is_a2_shape` detector).
        let full = A2Shape::Full.layer_configs();
        let lite = A2Shape::Lite.layer_configs();
        assert_eq!(full[0].channels, 8);
        assert_eq!(full[0].bottleneck, 8);
        assert_eq!(lite[0].channels, 3);
        assert_eq!(lite[0].bottleneck, 3);
        for cfg in [&full[0], &lite[0]] {
            assert_eq!(cfg.channels, cfg.bottleneck);
            assert_eq!(cfg.kernel_sizes.len(), 23);
            assert_eq!(cfg.head.kernel_size, 16);
            assert_eq!(cfg.head.head_dilation, 1);
            assert_eq!(cfg.head.out_channels, 1);
        }
    }

    #[test]
    fn a2_bottleneck_probe_shape_has_bottleneck_not_equal_channels() {
        // The entire point of this shape (see A2Shape::BottleneckProbe's doc comment): exercise
        // bottleneck != channels, which neither real A2 shape ever does.
        let cfg = &A2Shape::BottleneckProbe.layer_configs()[0];
        assert_ne!(
            cfg.channels, cfg.bottleneck,
            "BottleneckProbe must have bottleneck != channels"
        );
    }

    #[test]
    fn a2_full_has_more_weights_than_lite() {
        let full = generate_a2(A2Shape::Full, 1).unwrap();
        let lite = generate_a2(A2Shape::Lite, 1).unwrap();
        assert!(
            full.weights.len() > lite.weights.len(),
            "expected Full to have strictly more weights than Lite: {} vs {}",
            full.weights.len(),
            lite.weights.len()
        );
    }

    const LSTM_SHAPES: [LstmShape; 3] = [LstmShape::Standard, LstmShape::Small, LstmShape::Tiny];

    #[test]
    fn generates_lstm_without_error_for_all_shapes() {
        for shape in LSTM_SHAPES {
            generate_lstm(shape, 1).unwrap_or_else(|e| panic!("{shape:?}: {e}"));
        }
    }

    #[test]
    fn lstm_generation_is_deterministic_for_a_given_seed() {
        let a = generate_lstm(LstmShape::Standard, 42).unwrap();
        let b = generate_lstm(LstmShape::Standard, 42).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn different_seeds_produce_different_lstm_weights() {
        let a = generate_lstm(LstmShape::Standard, 1).unwrap();
        let b = generate_lstm(LstmShape::Standard, 2).unwrap();
        assert_ne!(a.weights, b.weights);
    }

    #[test]
    fn lstm_shapes_have_decreasing_weight_counts() {
        let sizes: Vec<usize> = LSTM_SHAPES
            .iter()
            .map(|&s| generate_lstm(s, 1).unwrap().weights.len())
            .collect();
        for w in sizes.windows(2) {
            assert!(
                w[0] > w[1],
                "expected strictly decreasing weight counts: {sizes:?}"
            );
        }
    }

    #[test]
    fn lstm_model_round_trips_through_json() {
        for shape in LSTM_SHAPES {
            let model = generate_lstm(shape, 7).unwrap();
            let bytes = model.to_json_bytes();
            let parsed = LstmModel::from_json_bytes(&bytes).expect("round trip parses");
            assert_eq!(model, parsed, "{shape:?} did not round-trip");
        }
    }

    #[test]
    fn generated_lstm_models_have_bounded_nondegenerate_rms() {
        let probe = calibration_probe(999);
        for shape in LSTM_SHAPES {
            let model = generate_lstm(shape, 999).unwrap();
            let rms = measure_lstm_output_rms(&model, &probe);
            assert!(rms.is_finite(), "{shape:?}: non-finite RMS");
            assert!(rms > 1e-4, "{shape:?}: near-silent, RMS = {rms}");
            assert!(rms < 10.0, "{shape:?}: divergent, RMS = {rms}");
        }
    }

    #[test]
    fn lstm_config_always_uses_scope_restricted_channel_widths() {
        // namir-nam's lstm.rs only supports input_size == in_channels == out_channels == 1; a
        // generator that ever emitted anything else would have no consumer to validate it.
        for shape in LSTM_SHAPES {
            let cfg = shape.config();
            assert_eq!(cfg.input_size, 1, "{shape:?}: input_size");
            assert_eq!(cfg.in_channels, 1, "{shape:?}: in_channels");
            assert_eq!(cfg.out_channels, 1, "{shape:?}: out_channels");
        }
    }
}
