// Instantiates the S-5 module. Kept free of DOM and Worker APIs so both the
// AudioWorklet (Task 6) and the Node parity runner can reuse it.
export async function loadNamir(wasmBytes, nowUs) {
  const { instance } = await WebAssembly.instantiate(wasmBytes, {
    env: { now_us: nowUs },
  });
  return { exports: instance.exports, memory: instance.exports.memory };
}

export function writeBytes(mod, bytes) {
  const ptr = mod.exports.alloc(bytes.length);
  // Read `.buffer` after `alloc`: growing linear memory detaches the old ArrayBuffer.
  new Uint8Array(mod.memory.buffer, ptr, bytes.length).set(bytes);
  return ptr;
}

/// Error energy of `got` relative to `want`, in dB. `want` all-zero would mean the
/// reference itself is silent; report that as +Infinity rather than NaN, so it can
/// never be mistaken for a pass.
export function dbBetween(got, want, n) {
  let num = 0, den = 0;
  for (let i = 0; i < n; i++) {
    const d = got[i] - want[i];
    num += d * d;
    den += want[i] * want[i];
  }
  return den === 0 ? Infinity : 10 * Math.log10(num / den);
}

export function f32(bytes, n) {
  return new Float32Array(bytes.buffer, bytes.byteOffset, n);
}

/// The parity criterion (coordinator ruling, fix round 1). The original spec bar was an
/// absolute -100 dB; it is unreachable by *any* build of this chain, so it tested
/// nothing. The criterion is relative instead: the wasm-vs-native residual must sit
/// within CONTROL_MARGIN_DB of the native-vs-native control, and the control is
/// measured in this same run from two native renders rather than hardcoded.
export const CONTROL_MARGIN_DB = 3.0;

export function parity(mod, refBytes, controlBytes, samples) {
  // render() can grow linear memory, so read `.buffer` only after it returns.
  const ptr = mod.exports.render(samples);
  const got = new Float32Array(mod.memory.buffer, ptr, samples);
  const want = f32(refBytes, samples);
  const control = dbBetween(f32(controlBytes, samples), want, samples);

  // The control must be checked before it is trusted. Both fixtures are gitignored and
  // regenerated by hand, so a degenerate control -- silent, truncated, or accidentally a
  // copy of the reference -- is reachable in practice. With control ~ 0 dB the relative
  // bar collapses to an absolute 3 dB, and under that a SILENT wasm chain scoring
  // 0.00 dB would PASS, inverting the one check this whole spike rests on. Assert the
  // property directly rather than a proxy for it: a silent render must not pass.
  const silence = dbBetween(new Float32Array(samples), want, samples);
  if (!(silence - control > CONTROL_MARGIN_DB)) {
    throw new Error(
      `degenerate control render: ${control.toFixed(2)} dB against the reference -- ` +
      `a silent chain (${silence.toFixed(2)} dB) would pass the ${CONTROL_MARGIN_DB} dB ` +
      `bar. Regenerate fixtures/reference_control_f32le.bin; see RESULTS.md.`,
    );
  }

  const residual = dbBetween(got, want, samples);
  return { residual, control, margin: residual - control, pass: residual - control <= CONTROL_MARGIN_DB };
}
