//! FR-UI-110's brand mark: the wordmark-plus-leopard-head that replaced `ui.heading("Namir")` in
//! [`crate::app::render`]'s top panel.
//!
//! # Why an alpha mask rather than a PNG
//!
//! The artwork (`images/namir.png`) is a single fill, `#ff6600`, on a transparent background, so
//! every bit of shape and anti-aliasing information in it lives in the alpha channel. That makes
//! an 8-bit alpha mask a *colour-lossless* re-encoding of it: the three channels dropped carry
//! nothing [`MARK_FILL`] does not already carry, and `xtask`'s decoder refuses artwork that
//! premise is false for rather than flattening it to one colour in silence.
//!
//! Colour is the only axis on which nothing is lost. The blob is also **downsampled**, 1767x474
//! to 358x96, which is an ordinary and deliberate loss of resolution — sized in
//! `xtask/src/identity.rs`'s `MARK_TARGET_HEIGHT` against how large the mark is actually drawn,
//! and not to be read as part of the losslessness claim.
//!
//! What the re-encoding buys is that this crate renders the mark while gaining **no new dependency
//! at all**. There is no image decoder in `namir-ui`, in `namir-app` or in `namir-clap`; the
//! decoder lives in `xtask`,
//! which is in neither product's dependency graph. `xtask/src/identity.rs` generates the blob and
//! CI (`cargo run -p xtask -- identity`) byte-compares it against a fresh render, so the embedded
//! bytes cannot drift from the artwork they were made from.
//!
//! # Blob format
//!
//! A `u32` width then a `u32` height, both little-endian, followed by `width * height` alpha
//! bytes, row-major, top to bottom. Nothing else — the colour is [`MARK_FILL`], a constant in this
//! file, not something the blob carries.
//!
//! # Texture lifetime
//!
//! The mask is tinted into an [`egui::ColorImage`] and uploaded **once per window**, and the
//! resulting [`egui::TextureHandle`] is cached in [`crate::ViewState`] — the same place every
//! other piece of this crate's own cross-frame view state lives — rather than through a
//! `Context::load_texture` call on every frame. `load_texture` allocates and queues a fresh
//! texture upload on each call, so calling it per frame would push ~34 KiB of pixel data at the
//! renderer sixty times a second for an image that never changes. Caching on `ViewState` (over,
//! say, an `egui::Id`-keyed entry in the context's temp memory) also keeps the handle's lifetime
//! tied to exactly the thing that owns it: the texture is freed when the window's view state is
//! dropped, with no shared-context key that could outlive it or collide with another window's.

use egui::{Color32, ColorImage, Image, TextureHandle, TextureOptions, Ui, Vec2};

/// The one colour the whole mark is drawn in: `#ff6600`.
pub const MARK_FILL: [u8; 3] = [0xff, 0x66, 0x00];

/// The mark's accessible name and hover text.
///
/// FR-UI-030 requires every control to carry an accessible name, and an image replacing a text
/// heading would otherwise *lose* one — the heading's own text was its name. `Image::alt_text`
/// sets the widget's `WidgetInfo::label`, which is what `egui` feeds its accesskit tree, so the
/// mark reads as "Namir" to an accessibility client exactly as the heading did. (The same honest
/// limitation `controls.rs` records applies: `egui-baseview` 0.6 does not forward that tree to a
/// platform screen reader yet.)
pub const ACCESSIBLE_NAME: &str = "Namir";

/// Generated by `cargo run -p xtask -- identity --write` from `images/namir.png`. Never hand-edit.
const MARK_ALPHA: &[u8] = include_bytes!("namir_mark.alpha");

/// How the mark's texture is filtered: bilinear, **with mipmaps**.
///
/// The mask is 358x96 and is drawn at `TextStyle::Heading` row height (~20-24 pt), so it is
/// *minified* by roughly 4-5x. That is the aliasing-prone direction, not the safe one: a bilinear
/// minification samples at most four texels of the twenty-odd that fall inside one screen pixel,
/// so thin strokes shimmer and drop out. `mipmap_mode` is what fixes it — the backend builds the
/// reduction chain once at upload and samples the level matching the on-screen size.
///
/// This is a real setting on this stack rather than an inert field: `egui-baseview` 0.6 renders
/// through `egui_glow` 0.35 (its default `opengl` feature), which is the one backend `epaint`
/// documents as honouring `mipmap_mode`, and which calls `glGenerateMipmap` on upload when it is
/// set.
const MARK_TEXTURE_OPTIONS: TextureOptions =
    TextureOptions::LINEAR.with_mipmap_mode(Some(egui::TextureFilter::Linear));

/// `(width, height, alpha bytes)` of the embedded mask.
///
/// Panics on a malformed blob, deliberately: the bytes are `include_bytes!`d at compile time and
/// checked in CI, so a failure here is a broken build artifact rather than anything a running user
/// could cause, and the unit tests below exercise it on every `cargo test`.
fn mask() -> (usize, usize, &'static [u8]) {
    assert!(
        MARK_ALPHA.len() >= 8,
        "the brand mark blob is shorter than its 8-byte header -- regenerate it with \
         `cargo run -p xtask -- identity --write`"
    );
    let width = u32::from_le_bytes(MARK_ALPHA[0..4].try_into().expect("4 bytes")) as usize;
    let height = u32::from_le_bytes(MARK_ALPHA[4..8].try_into().expect("4 bytes")) as usize;
    let pixels = &MARK_ALPHA[8..];
    assert_eq!(
        pixels.len(),
        width * height,
        "the brand mark blob's header says {width}x{height} but it carries {} alpha bytes -- \
         regenerate it with `cargo run -p xtask -- identity --write`",
        pixels.len()
    );
    (width, height, pixels)
}

/// The mark as an `egui` image: every pixel [`MARK_FILL`] at the mask's alpha.
///
/// `epaint` textures are **premultiplied**, so the tint is applied here at construction rather
/// than left to a shader or to a per-frame tint colour: each channel is scaled by the pixel's own
/// alpha with integer arithmetic (`(channel * a + 127) / 255`), which keeps a fully transparent
/// texel at exactly `Color32::TRANSPARENT` and so leaves no coloured fringe around the glyph
/// edges when the mark is minified.
pub fn mark_image() -> ColorImage {
    let (width, height, alpha) = mask();
    let pixels = alpha
        .iter()
        .map(|&a| {
            let scale = |c: u8| ((u32::from(c) * u32::from(a) + 127) / 255) as u8;
            Color32::from_rgba_premultiplied(
                scale(MARK_FILL[0]),
                scale(MARK_FILL[1]),
                scale(MARK_FILL[2]),
                a,
            )
        })
        .collect();
    ColorImage::new([width, height], pixels)
}

/// How many `TextStyle::Heading` rows tall the mark is drawn.
///
/// It stood at exactly one row until M12's manual test was executed on Windows, where the verdict
/// on both shells was that the mark read as too small -- one heading row is ~25 logical pixels,
/// which is a line of text rather than a logo.
///
/// Two is also the largest factor that costs nothing in sharpness. The blob is
/// [`MARK_TARGET_HEIGHT`](../../../../xtask/src/identity.rs) = 96 rows, so at two heading rows
/// (~50 logical pixels) a 2x HiDPI display asks for ~100 physical pixels against 96 stored -- a
/// ~1.04x magnification, effectively 1:1 and the sharpest this asset can be drawn. Going higher
/// magnifies a mask that has no more detail to give, and wants a taller blob instead.
const MARK_HEIGHT_IN_HEADINGS: f32 = 2.0;

/// Draws the mark into `ui`, uploading its texture through `cache` on the first frame only.
///
/// Scaled to [`MARK_HEIGHT_IN_HEADINGS`] heading rows, so the top panel is taller than the
/// `ui.heading("Namir")` this mark replaced -- deliberately, and nothing else in the panel moves
/// relative to it.
pub fn render(ui: &mut Ui, cache: &mut Option<TextureHandle>) {
    let row_height = ui.text_style_height(&egui::TextStyle::Heading) * MARK_HEIGHT_IN_HEADINGS;
    let texture = cache.get_or_insert_with(|| {
        ui.ctx()
            .load_texture("namir_brand_mark", mark_image(), MARK_TEXTURE_OPTIONS)
    });

    let [width, height] = texture.size();
    let size = Vec2::new(row_height * width as f32 / height.max(1) as f32, row_height);

    ui.add(Image::new((texture.id(), size)).alt_text(ACCESSIBLE_NAME))
        .on_hover_text(ACCESSIBLE_NAME);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_embedded_blob_is_a_well_formed_mask() {
        let (width, height, alpha) = mask();
        assert!(width > 0 && height > 0);
        assert_eq!(alpha.len(), width * height);
        // The mark is a wordmark: much wider than it is tall, and not a solid rectangle.
        assert!(width > height);
        assert!(alpha.contains(&0), "no transparent texel at all");
        assert!(alpha.iter().any(|&a| a > 0), "the mask is entirely empty");
    }

    #[test]
    fn every_pixel_is_the_brand_fill_at_the_mask_alpha() {
        let image = mark_image();
        let (width, height, alpha) = mask();
        assert_eq!(image.size, [width, height]);
        assert_eq!(image.pixels.len(), alpha.len());

        for (pixel, &a) in image.pixels.iter().zip(alpha) {
            assert_eq!(pixel.a(), a);
            // Premultiplied: no channel may exceed its own alpha, or the texel would brighten
            // where it should fade.
            assert!(pixel.r() <= a && pixel.g() <= a && pixel.b() <= a);
            assert_eq!(pixel.b(), 0, "the fill has no blue component");
        }

        let opaque = image
            .pixels
            .iter()
            .find(|p| p.a() == 255)
            .expect("the mark has fully opaque texels");
        assert_eq!(
            [opaque.r(), opaque.g(), opaque.b()],
            MARK_FILL,
            "a fully opaque texel is the brand fill exactly"
        );

        let clear = image.pixels.iter().find(|p| p.a() == 0);
        if let Some(clear) = clear {
            assert_eq!(*clear, Color32::TRANSPARENT);
        }
    }

    fn frame_input() -> egui::RawInput {
        egui::RawInput {
            screen_rect: Some(egui::Rect::from_min_size(
                egui::Pos2::ZERO,
                egui::vec2(400.0, 300.0),
            )),
            ..Default::default()
        }
    }

    /// FR-UI-030: replacing the `ui.heading("Namir")` this mark stands in for must not cost the
    /// top panel its accessible name. Asserted against the real accesskit tree `egui` emits --
    /// `Image::alt_text` -> `WidgetInfo::label` -> `accesskit::Node::label` -- not against the
    /// builder call, so a future `egui` that stopped forwarding alt text would fail here.
    #[test]
    fn the_mark_carries_namir_as_its_accessible_name() {
        let ctx = egui::Context::default();
        ctx.enable_accesskit();
        let mut cache = None;

        let output = ctx.run_ui(frame_input(), |ui| render(ui, &mut cache));

        let update = output
            .platform_output
            .accesskit_update
            .expect("accesskit was enabled, so the frame emits a tree update");
        assert!(
            update
                .nodes
                .iter()
                .any(|(_, node)| node.label() == Some(ACCESSIBLE_NAME)),
            "no accesskit node is labelled `{ACCESSIBLE_NAME}` -- the mark lost the accessible \
             name the heading it replaced had"
        );
    }

    /// The mark occupies [`MARK_HEIGHT_IN_HEADINGS`] heading rows.
    ///
    /// Pinned as a test because the factor is not free to change: the blob is 96 rows, so two
    /// heading rows is already ~1:1 against it at a 2x HiDPI scale factor. Raising this without
    /// also raising `MARK_TARGET_HEIGHT` starts magnifying a mask with no more detail in it, and
    /// M12's manual test is the reason the figure is 2.0 rather than the 1.0 it shipped at.
    #[test]
    fn the_mark_is_drawn_at_two_heading_rows() {
        let ctx = egui::Context::default();
        let mut cache = None;
        let mut heading_height = 0.0;
        let mut mark_rect = egui::Rect::ZERO;

        let _ = ctx.run_ui(frame_input(), |ui| {
            heading_height = ui.text_style_height(&egui::TextStyle::Heading);
            let before = ui.next_widget_position();
            render(ui, &mut cache);
            mark_rect = egui::Rect::from_min_max(before, ui.min_rect().max);
        });

        assert!(heading_height > 0.0);
        let expected = heading_height * MARK_HEIGHT_IN_HEADINGS;
        assert!(
            (mark_rect.height() - expected).abs() < 1.0,
            "the mark is {} px tall against an expected {expected} px              ({MARK_HEIGHT_IN_HEADINGS} x a {heading_height} px heading row)",
            mark_rect.height()
        );
    }

    /// The mark is minified ~4-5x, so the texture must be uploaded with mipmapping on or a
    /// bilinear minification will alias it. Nothing about that is visible from a headless test, so
    /// what is asserted is the upload itself: the options `egui` recorded for the allocated
    /// texture, read back from its own texture manager rather than from the constant this file
    /// passes in.
    #[test]
    fn the_texture_is_uploaded_with_mipmapping_enabled() {
        let ctx = egui::Context::default();
        let mut cache = None;
        let _ = ctx.run_ui(frame_input(), |ui| render(ui, &mut cache));

        let id = cache.as_ref().expect("uploaded on the first frame").id();
        let manager = ctx.tex_manager();
        let manager = manager.read();
        let meta = manager.meta(id).expect("the texture is allocated");

        assert_eq!(
            meta.options.mipmap_mode,
            Some(egui::TextureFilter::Linear),
            "the brand mark was uploaded without mipmaps -- it aliases when minified"
        );
        assert_eq!(meta.options.minification, egui::TextureFilter::Linear);
        assert_eq!(meta.options.magnification, egui::TextureFilter::Linear);
    }

    #[test]
    fn the_texture_is_uploaded_once_and_reused() {
        let ctx = egui::Context::default();
        let mut cache = None;

        let _ = ctx.run_ui(egui::RawInput::default(), |ui| render(ui, &mut cache));
        let first = cache.as_ref().expect("uploaded on the first frame").id();

        for _ in 0..4 {
            let _ = ctx.run_ui(egui::RawInput::default(), |ui| render(ui, &mut cache));
        }

        assert_eq!(
            cache.as_ref().expect("still cached").id(),
            first,
            "a later frame re-uploaded the mark instead of reusing its texture"
        );
    }
}
