#!/bin/bash
#
# make_installer.sh -- build Namir's macOS distribution: a `.pkg` inside a `.dmg`, plus the plain
# archive FR-PKG-050 asks for. M13, D-18.3's macOS leg.
#
# ---------------------------------------------------------------------------------------------
# WHAT THIS CONSUMES, AND WHY IT DOES NOT BUILD ANYTHING
# ---------------------------------------------------------------------------------------------
# D-18.3 fixes the release order: build -> `xtask bundle` -> per-OS package -> GitHub Release.
# This script is the third step and only the third step. Its input is the staging tree
# `cargo run -p xtask -- bundle --target macos` produces at `target/bundle/macos`:
#
#     Namir.clap/Contents/Info.plist          (generated by xtask, byte-checked by `bundle --check`)
#     Namir.clap/Contents/PkgInfo             (the eight bytes `BNDL????`)
#     Namir.clap/Contents/MacOS/libnamir_clap.dylib
#     Namir.app/Contents/Info.plist           (APPL, and NSMicrophoneUsageDescription)
#     Namir.app/Contents/PkgInfo              (the eight bytes `APPL????`)
#     Namir.app/Contents/MacOS/namir          (the standalone executable)
#     THIRD-PARTY-NOTICES.md
#     LICENSE-MIT
#     LICENSE-APACHE
#     README.md
#     TRADEMARK.md
#
# That list is `xtask/src/bundle.rs`'s `plan(Platform::MacOs)`, and it is deliberately the *only*
# thing this script trusts: what ships is what `bundle --check` already asserted. `verify_staging`
# below re-asserts it anyway, because a staging tree that arrived through a CI artifact upload is
# not the one `--check` looked at (see the chmod note in `assemble_payloads`).
#
# ---------------------------------------------------------------------------------------------
# WHY A `.pkg` INSIDE A `.dmg`, AND NOT A BARE `.dmg` (D-18.3, verbatim reasons)
# ---------------------------------------------------------------------------------------------
# (a) A release places multiple payloads at multiple absolute paths -- the `.clap` bundle under
#     `~/Library/Audio/Plug-Ins/CLAP` or `/Library/Audio/Plug-Ins/CLAP` (D-13.3's macOS row), the
#     standalone under `/Applications`, the attribution file and licence texts with them. Only
#     `pkgbuild`/`productbuild` can express that. A `.dmg` is a mountable folder the user drags
#     from, which handles one destination well and several badly.
# (b) Files placed by `installer` from a `.pkg` do not carry `com.apple.quarantine`. Files a user
#     extracts from a downloaded zip do. A quarantined plugin is exactly risk R-11.
#
# The `.dmg` is then only a delivery container for the `.pkg` -- it is what a browser downloads and
# what notarisation staples cleanly.
#
# ---------------------------------------------------------------------------------------------
# THE HONEST CAVEAT -- READ THIS BEFORE SHIPPING A macOS BUILD TO ANYONE (risk R-11, D-18.3)
# ---------------------------------------------------------------------------------------------
# An unsigned, quarantined **plugin** does not fail the way an unsigned application does. An
# application gets Gatekeeper's "Open Anyway" path. A plugin loaded by a DAW gets **no
# user-visible override at all** -- it simply fails to load, with no dialog and nothing in the
# host's UI to click -- and macOS 15 removed the Control-click bypass that used to work.
#
# Until a signing identity exists, **a macOS release of Namir is developer-only in practice.**
# Say so in the release notes; do not let a user discover it. This script prints the same caveat
# at the end of every unsigned run, and puts it in the installer's own welcome pane, so the
# statement travels with the artifact rather than living only in `docs/`.
#
# ---------------------------------------------------------------------------------------------
# SIGNING IS CONDITIONAL ON A SECRET BEING PRESENT, NOT ON A BUILD FLAG (D-18.3, Surge's pattern)
# ---------------------------------------------------------------------------------------------
# There is no `--sign` flag here and there must never be one. Each signing step reads an
# environment variable, does nothing when it is empty, and the run continues down the identical
# sequence of steps either way:
#
#   NAMIR_CODESIGN_IDENTITY    "Developer ID Application: ..."  -- signs Namir.clap and Namir.app
#   NAMIR_INSTALLER_IDENTITY   "Developer ID Installer: ..."    -- signs the .pkg (productbuild)
#   NAMIR_NOTARY_PROFILE       a `notarytool store-credentials` keychain profile name
#     ...or NAMIR_NOTARY_APPLE_ID + NAMIR_NOTARY_TEAM_ID + NAMIR_NOTARY_PASSWORD
#
# Two identities, not one, because Apple issues two: `codesign` needs "Developer ID Application"
# and `productbuild` needs "Developer ID Installer". Each is independently optional, so a workflow
# that has one and not the other still gets the half it can do.
#
# Turning notarisation on later is: add the secrets. No restructuring, no new code path, and the
# unsigned path stays the one exercised on every run rather than an untested fallback.
#
# ---------------------------------------------------------------------------------------------
# WHAT HAS NEVER BEEN RUN
# ---------------------------------------------------------------------------------------------
# All of it. This script was written on Windows, against the documented behaviour of `pkgbuild`,
# `productbuild`, `hdiutil`, `ditto` and `notarytool` and against Surge's `make_installer.sh` as
# D-18.3's named reference. No line of it has executed on a Mac. `packaging/macos/README.md`
# lists the specific parts most likely to be wrong; the per-user install domain is first on it.
#
# Reference: Surge XT's `installer_mac/make_installer.sh` (D-18.3 names it), Apple's Distribution
# XML reference, and `man pkgbuild` / `man productbuild`.

set -euo pipefail

# ------------------------------------------------------------------------------------------------
# Identity constants. These mirror values that already exist elsewhere in the tree; each is a second
# copy of a literal for the same reason `xtask/src/bundle.rs` keeps its own copy of `PLUGIN_ID` --
# nothing here is in either shipped product's dependency graph, so there is nothing to import from.
# If one of these changes, the other copy is named in the comment beside it.
# ------------------------------------------------------------------------------------------------

# `xtask/src/bundle.rs`'s BUNDLE_NAME, and `crates/namir-app/Cargo.toml`'s [[bin]] name capitalised.
readonly PRODUCT_NAME="Namir"
# `xtask/src/bundle.rs`'s BUNDLE_IDENTIFIER == `crates/namir-clap/src/lib.rs`'s PLUGIN_ID.
readonly PLUGIN_BUNDLE_ID="org.legrand.namir"
# The standalone's own bundle identifier. NOT the same string as PLUGIN_BUNDLE_ID: CFBundleIdentifier
# must be unique per bundle, and this one is what TCC keys the microphone grant on. See
# `xtask/src/bundle.rs`'s APP_BUNDLE_IDENTIFIER, which is where the decision now lives and is
# argued -- this script had to answer it to function at all, and M13 moved the answer to the tool
# that generates the plist rather than leaving it in a packaging script.
readonly APP_BUNDLE_ID="org.legrand.namir.standalone"

# Component package identifiers. Distinct per component, or `installer` treats an upgrade of one as
# a replacement of another. These are package ids, not bundle ids -- unrelated namespaces.
readonly PKG_ID_PLUGIN="org.legrand.namir.clap.pkg"
readonly PKG_ID_APP="org.legrand.namir.app.pkg"
readonly PKG_ID_DOCS="org.legrand.namir.docs.pkg"

# D-13.3's macOS row, system-wide cells. The per-user cells are NOT separate paths here: the
# distribution's `<domains enable_currentUserHome="true">` makes `installer` re-root these under the
# user's home when they choose "Install for me only", so `/Library/Audio/Plug-Ins/CLAP` becomes
# `~/Library/Audio/Plug-Ins/CLAP` and `/Applications` becomes `~/Applications`. One install-location
# per component yielding both of D-13.3's cells is the same trick Inno's `{autocf}` plays on Windows.
readonly INSTALL_LOCATION_PLUGIN="/Library/Audio/Plug-Ins/CLAP"
readonly INSTALL_LOCATION_APP="/Applications"
# FR-PKG-040's three files land here rather than beside the app, so they exist even if a user
# deselects the standalone. `Legal/` rather than the directory root: `~/Library/Application
# Support/Namir` is D-13.2's config directory, where `namir-platform` writes real runtime state, and
# an installer dropping files into it should not risk a name collision with one of them.
readonly INSTALL_LOCATION_DOCS="/Library/Application Support/${PRODUCT_NAME}/Legal"

# The staging tree's contents, exactly as `plan(Platform::MacOs)` returns them.
readonly CLAP_ARTIFACT="Namir.clap"
readonly CLAP_DYLIB="libnamir_clap.dylib"
readonly STANDALONE_BIN="namir"
# M13: `plan(Platform::MacOs)` stages the standalone as an application bundle, not a bare
# Mach-O. See "Step 2a" below for why that is a correctness requirement rather than a Finder
# nicety.
readonly APP_ARTIFACT="Namir.app"
# FR-PKG-040's enumerated set (`bundle.rs`'s LICENCE_DOCUMENTS), then the two documents staged
# beside them. TRADEMARK.md is not an FR-PKG-040 file -- that set is exactly three, named by the
# requirement -- but the staged README's licence section points at it, and NFR-LIC-070 wants the
# mark's terms stated wherever the mark travels. The shipped binaries carry the mark.
readonly LICENCE_DOCUMENTS="THIRD-PARTY-NOTICES.md LICENSE-MIT LICENSE-APACHE"
readonly STAGED_DOCUMENTS="${LICENCE_DOCUMENTS} README.md TRADEMARK.md"

readonly MIN_MACOS_VERSION="11.0"

# ------------------------------------------------------------------------------------------------
# Plumbing
# ------------------------------------------------------------------------------------------------

log()  { printf 'make_installer: %s\n' "$*"; }
step() { printf '\nmake_installer: == %s\n' "$*"; }
die()  { printf 'make_installer: error: %s\n' "$*" >&2; exit 1; }

usage() {
	cat <<'USAGE'
usage: make_installer.sh [--staging DIR] [--out DIR] [--version V] [--skip-verify]

  --staging DIR   the tree `xtask bundle --target macos` produced
                  (default: $CARGO_TARGET_DIR/bundle/macos, else <repo>/target/bundle/macos)
  --out DIR       where the .pkg, .dmg, .zip and .sha256 files are written
                  (default: <repo>/target/packaging/macos)
  --version V     version string for filenames and CFBundleShortVersionString
                  (default: $NAMIR_VERSION, else the `version` in crates/namir-app/Cargo.toml)
  --skip-verify   skip the post-build expansion/mount checks (they need a few seconds and a
                  free /Volumes mount point; everything else still runs)

Signing is conditional on secrets, never on a flag -- see this script's header for the four
environment variables and for why there is no --sign.
USAGE
}

# Argument parsing is strict, and an unrecognised flag exits 2 rather than being ignored. Same
# reasoning as `xtask bundle`'s own parser: these flags select between *behaviours* and between
# *inputs*, so a typo that silently selected a different one would be worse than a loud refusal.
STAGING=""
OUT_DIR=""
VERSION=""
SKIP_VERIFY=0
while [ $# -gt 0 ]; do
	case "$1" in
		--staging) [ $# -ge 2 ] || die "--staging needs a value"; STAGING="$2"; shift 2 ;;
		--out)     [ $# -ge 2 ] || die "--out needs a value";     OUT_DIR="$2"; shift 2 ;;
		--version) [ $# -ge 2 ] || die "--version needs a value"; VERSION="$2"; shift 2 ;;
		--skip-verify) SKIP_VERIFY=1; shift ;;
		-h|--help) usage; exit 0 ;;
		*) printf 'make_installer: unrecognised argument `%s`\n\n' "$1" >&2; usage >&2; exit 2 ;;
	esac
done

[ "$(uname -s)" = "Darwin" ] || die "this script builds a macOS installer and needs macOS: pkgbuild,
 productbuild, hdiutil, ditto, codesign and notarytool have no counterpart on $(uname -s). The
 staging tree it consumes can be produced anywhere (\`xtask bundle\` is host-independent by
 design); the packaging cannot."

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

if [ -z "$STAGING" ]; then
	if [ -n "${CARGO_TARGET_DIR:-}" ]; then
		STAGING="${CARGO_TARGET_DIR}/bundle/macos"
	else
		STAGING="${REPO_ROOT}/target/bundle/macos"
	fi
fi
[ -n "$OUT_DIR" ] || OUT_DIR="${REPO_ROOT}/target/packaging/macos"

# Version: flag, else environment, else the standalone crate's own `version` key. The workspace has
# no `[workspace.package] version` -- each crate carries its own -- so `namir-app`'s is the one that
# describes the binary being packaged. Read with awk rather than a TOML parser because the shape is
# fixed: the first `version = "..."` after `[package]`.
if [ -z "$VERSION" ]; then
	VERSION="${NAMIR_VERSION:-}"
fi
if [ -z "$VERSION" ]; then
	VERSION="$(awk '/^\[package\]/{p=1} p && /^version *=/{gsub(/[",]/,"",$3); print $3; exit}' \
		"${REPO_ROOT}/crates/namir-app/Cargo.toml")"
fi
[ -n "$VERSION" ] || die "could not determine a version; pass --version"

readonly STAGING OUT_DIR VERSION SKIP_VERIFY
readonly WORK_DIR="${OUT_DIR}/work"
readonly PKG_NAME="${PRODUCT_NAME}-${VERSION}.pkg"
readonly DMG_NAME="${PRODUCT_NAME}-${VERSION}-macos.dmg"
readonly ZIP_NAME="${PRODUCT_NAME}-${VERSION}-macos.zip"

require_tools() {
	local missing=""
	local tool
	for tool in pkgbuild productbuild hdiutil ditto codesign pkgutil xcrun shasum awk; do
		command -v "$tool" >/dev/null 2>&1 || missing="${missing} ${tool}"
	done
	[ -x /usr/libexec/PlistBuddy ] || missing="${missing} /usr/libexec/PlistBuddy"
	[ -z "$missing" ] || die "missing required tool(s):${missing}. \
Install the Xcode command line tools (\`xcode-select --install\`)."
}

# ------------------------------------------------------------------------------------------------
# Step 1 -- the staging tree is exactly what `xtask bundle --target macos` produces
# ------------------------------------------------------------------------------------------------
# Every violation is collected and reported together rather than failing on the first, for the
# reason `bundle::check` gives in its own doc comment: a missing Info.plist must not hide an absent
# licence text, since a reader who fixes one and re-runs has learnt nothing about the other.
verify_staging() {
	step "verifying the staging tree at ${STAGING}"
	[ -d "$STAGING" ] || die "no staging tree at ${STAGING}.
 Run \`cargo build --release --workspace\` then \`cargo run -p xtask -- bundle --target macos\`."

	local violations=""
	local path

	# FR-PKG-020's structural half. A plain file here is the specific mistake the requirement
	# exists to catch, so it is reported as itself.
	if [ -f "${STAGING}/${CLAP_ARTIFACT}" ]; then
		violations="${violations}\n  ${CLAP_ARTIFACT} is a plain file -- on macOS the CLAP artifact\
 must be a bundle directory; a renamed dylib is something no host will load"
	elif [ ! -d "${STAGING}/${CLAP_ARTIFACT}" ]; then
		violations="${violations}\n  ${CLAP_ARTIFACT} is absent"
	fi

	# The same check for the application bundle, for the same reason at one remove: a bare Mach-O
	# cannot declare `NSMicrophoneUsageDescription`, which macOS 10.14+ requires before a process
	# may open an audio *input* device -- the whole product for an instrument amplifier simulator.
	if [ -f "${STAGING}/${APP_ARTIFACT}" ]; then
		violations="${violations}\n  ${APP_ARTIFACT} is a plain file -- the standalone must be an\
 application bundle, or macOS denies it the audio input device it exists to process"
	elif [ ! -d "${STAGING}/${APP_ARTIFACT}" ]; then
		violations="${violations}\n  ${APP_ARTIFACT} is absent -- a staging tree from before M13\
 added it; re-run \`cargo run -p xtask -- bundle --target macos\`"
	fi

	for path in \
		"${CLAP_ARTIFACT}/Contents/Info.plist" \
		"${CLAP_ARTIFACT}/Contents/PkgInfo" \
		"${CLAP_ARTIFACT}/Contents/MacOS/${CLAP_DYLIB}" \
		"${APP_ARTIFACT}/Contents/Info.plist" \
		"${APP_ARTIFACT}/Contents/PkgInfo" \
		"${APP_ARTIFACT}/Contents/MacOS/${STANDALONE_BIN}" \
		${STAGED_DOCUMENTS}
	do
		[ -f "${STAGING}/${path}" ] || violations="${violations}\n  ${path} is absent"
	done

	if [ -n "$violations" ]; then
		# shellcheck disable=SC2059  # the violations string carries its own \n escapes
		printf 'make_installer: error: the staging tree is not the form macOS requires:%b\n' \
			"$violations" >&2
		die "re-run \`cargo run -p xtask -- bundle --target macos\` and fix what it reports"
	fi
	log "staging tree is the layout plan(Platform::MacOs) describes"
}

# ------------------------------------------------------------------------------------------------
# Step 2 -- payload roots, one per component package
# ------------------------------------------------------------------------------------------------
# `pkgbuild --root DIR --install-location PATH` maps the *contents* of DIR onto PATH, so each
# component needs its own root containing only what belongs at that destination. Three roots:
#
#   roots/plugin/Namir.clap              -> /Library/Audio/Plug-Ins/CLAP  (or ~/Library/...)
#   roots/app/Namir.app                  -> /Applications                 (or ~/Applications)
#   roots/docs/{the four documents}      -> /Library/Application Support/Namir/Legal
assemble_payloads() {
	step "assembling payload roots under ${WORK_DIR}"
	rm -rf "$WORK_DIR"
	mkdir -p "${WORK_DIR}/roots/plugin" "${WORK_DIR}/roots/app" "${WORK_DIR}/roots/docs" \
		"${WORK_DIR}/pkgs" "${WORK_DIR}/resources" "${WORK_DIR}/dmg" "${WORK_DIR}/archive"

	# `ditto` rather than `cp -R` throughout: it is the tool that preserves a bundle's symlinks,
	# extended attributes and resource forks intact, which matters once a bundle is signed --
	# `codesign` writes its signature into the bundle and a lossy copy invalidates it.
	ditto "${STAGING}/${CLAP_ARTIFACT}" "${WORK_DIR}/roots/plugin/${CLAP_ARTIFACT}"

	ditto "${STAGING}/${APP_ARTIFACT}" "${WORK_DIR}/roots/app/${APP_ARTIFACT}"
	# A CI artifact download does not preserve the executable bit: a staging tree that
	# travelled through `actions/upload-artifact` arrives at 0644 and the .app then fails to
	# launch with a message that says nothing useful. Set it rather than assume it.
	chmod 755 "${WORK_DIR}/roots/app/${APP_ARTIFACT}/Contents/MacOS/${STANDALONE_BIN}"

	local document
	for document in ${STAGED_DOCUMENTS}; do
		ditto "${STAGING}/${document}" "${WORK_DIR}/roots/docs/${document}"
	done

	# FR-PKG-040, asserted against the assembled payload rather than against the plan that
	# produced it -- the requirement is about what a distribution contains.
	for document in ${LICENCE_DOCUMENTS}; do
		[ -f "${WORK_DIR}/roots/docs/${document}" ] \
			|| die "FR-PKG-040: ${document} is missing from the docs payload"
	done

	log "payload roots assembled"
}

# ------------------------------------------------------------------------------------------------
# Step 2a -- removed at M13, and worth recording rather than deleting silently
# ------------------------------------------------------------------------------------------------
# This script used to carry an `assemble_standalone_app` function that wrapped the staged bare
# `namir` binary into a minimal `.app`, because `xtask bundle`'s macOS layout staged the standalone
# unbundled. That was a real defect and not a Finder nicety: an unbundled process has no
# `Info.plist`, so it cannot declare `NSMicrophoneUsageDescription`, which macOS 10.14+ requires
# before a process may open an audio *input* device -- and an instrument amplifier simulator that
# is denied its input is not a product. A bare executable in /Applications also opens Terminal on
# double-click.
#
# `plan(Platform::MacOs)` now stages `Namir.app/Contents/{Info.plist, PkgInfo, MacOS/namir}`, so
# the wrapper is gone rather than kept as a fallback. That is deliberate: the wrapper's own comment
# said it was "the one payload `xtask bundle --check` never asserted", and a fallback that silently
# produces an unasserted bundle from a stale staging tree is worse than a loud failure.
# `verify_staging` now refuses such a tree by name.


# ------------------------------------------------------------------------------------------------
# Step 3 -- code signing (conditional on a secret, per D-18.3)
# ------------------------------------------------------------------------------------------------
# Called unconditionally and at the same point in the sequence whether or not an identity exists.
# `codesign` cannot be invoked without an identity -- there is no "sign with nothing" -- so the
# conditional is inside this one function and nowhere else, which is what keeps every other step
# byte-identical between a signed and an unsigned run.
#
# `--options runtime` (the hardened runtime) and `--timestamp` are not optional extras: notarisation
# rejects a submission without them. `--deep` is deprecated by Apple for signing, so the bundle's
# inner Mach-O is signed first and the bundle wrapper second -- inside-out, which is what `--deep`
# was doing badly.
codesign_payloads() {
	step "code signing"
	if [ -z "${NAMIR_CODESIGN_IDENTITY:-}" ]; then
		log "NAMIR_CODESIGN_IDENTITY is unset -- skipping. The artifacts will be UNSIGNED;"
		log "see this script's header, and risk R-11 in docs/02-architecture.md section 22."
		return 0
	fi

	local identity="${NAMIR_CODESIGN_IDENTITY}"
	log "signing with: ${identity}"

	codesign --force --timestamp --options runtime --sign "$identity" \
		"${WORK_DIR}/roots/plugin/${CLAP_ARTIFACT}/Contents/MacOS/${CLAP_DYLIB}"
	codesign --force --timestamp --options runtime --sign "$identity" \
		"${WORK_DIR}/roots/plugin/${CLAP_ARTIFACT}"

	codesign --force --timestamp --options runtime --sign "$identity" \
		"${WORK_DIR}/roots/app/${PRODUCT_NAME}.app/Contents/MacOS/${STANDALONE_BIN}"
	codesign --force --timestamp --options runtime --sign "$identity" \
		"${WORK_DIR}/roots/app/${PRODUCT_NAME}.app"

	codesign --verify --strict --verbose=2 "${WORK_DIR}/roots/plugin/${CLAP_ARTIFACT}"
	codesign --verify --strict --verbose=2 "${WORK_DIR}/roots/app/${PRODUCT_NAME}.app"
	log "signed and verified"
}

# ------------------------------------------------------------------------------------------------
# Step 4 -- component packages
# ------------------------------------------------------------------------------------------------
# `BundleIsRelocatable` false on every bundle in every component. Left true (the default for
# bundle types that can relocate), `installer` looks for an existing copy of the bundle anywhere on
# the volume via Spotlight and installs *over that* instead of at the stated install-location -- so
# a developer with a `Namir.app` in a scratch directory gets the release written into their scratch
# directory and nothing at `/Applications` at all. This is the single best-known `pkgbuild` trap and
# the reason `--analyze` exists.
#
# **Detect bundles by `RootRelativeBundlePath`, never by `BundleIsRelocatable`.** That is the whole
# lesson of this function and it was learned the hard way, twice, on 2026-08-12:
#
#   1. The first tagged pipeline run (v0.1.0-rc1) died here with "found no bundle under
#      roots/plugin", because the loop below probed each entry for `BundleIsRelocatable` and treated
#      a failed probe as "no more entries".
#   2. The conclusion drawn from that -- that `pkgbuild` does not consider a `.clap` a bundle at
#      all, since `.clap` is not one of the extensions macOS knows -- was **wrong**, and a run on a
#      real Mac disproved it. `--analyze` over the plugin root emits exactly one entry, carrying
#      `RootRelativeBundlePath = Namir.clap`, `BundleIsVersionChecked` and `BundleOverwriteAction`.
#      What it omits is `BundleIsRelocatable`, which it writes only for bundle types that *can*
#      relocate. Probing for that key therefore conflates "there is no bundle" with "there is a
#      bundle which cannot relocate" -- two very different things, and the second is what a `.clap`
#      is. The built `PackageInfo` settles it: `relocatable="false"`, an empty `<relocate/>`, and
#      `<bundle id="org.legrand.namir" path="./Namir.clap"/>` present.
#
# So both roots are handled identically and neither is special-cased: count entries by a key every
# entry has, then force `BundleIsRelocatable` false on each with `Add`-then-`Set`, since `Add` fails
# when the key exists and `Set` fails when it does not, and which applies depends on the bundle
# type. The result for a `.clap` is the same `relocatable="false"` `pkgbuild` would have produced on
# its own -- but stated by this script rather than inherited from a default, which is the difference
# between a property that holds and a property that is asserted.
component_pkg() {
	local root="$1" identifier="$2" install_location="$3" out="$4"
	local plist="${WORK_DIR}/$(basename "$out").component.plist"

	pkgbuild --analyze --root "$root" "$plist"

	local i=0
	while /usr/libexec/PlistBuddy -c "Print :${i}:RootRelativeBundlePath" "$plist" >/dev/null 2>&1; do
		/usr/libexec/PlistBuddy -c "Add :${i}:BundleIsRelocatable bool false" "$plist" >/dev/null 2>&1 ||
			/usr/libexec/PlistBuddy -c "Set :${i}:BundleIsRelocatable false" "$plist"
		i=$((i + 1))
	done
	[ "$i" -gt 0 ] || die "pkgbuild --analyze found no bundle under ${root} -- every payload root\
 this is called for contains one, so an empty component list means the payload is not what this\
 script assembled"

	pkgbuild \
		--root "$root" \
		--component-plist "$plist" \
		--identifier "$identifier" \
		--version "$VERSION" \
		--install-location "$install_location" \
		"$out"
}

build_component_pkgs() {
	step "building component packages"

	component_pkg \
		"${WORK_DIR}/roots/plugin" "$PKG_ID_PLUGIN" "$INSTALL_LOCATION_PLUGIN" \
		"${WORK_DIR}/pkgs/plugin.pkg"

	component_pkg \
		"${WORK_DIR}/roots/app" "$PKG_ID_APP" "$INSTALL_LOCATION_APP" \
		"${WORK_DIR}/pkgs/app.pkg"

	# No component plist for the documents: there is no bundle in that root, so `--analyze` would
	# produce an empty array and `BundleIsRelocatable` has nothing to apply to.
	pkgbuild \
		--root "${WORK_DIR}/roots/docs" \
		--identifier "$PKG_ID_DOCS" \
		--version "$VERSION" \
		--install-location "$INSTALL_LOCATION_DOCS" \
		"${WORK_DIR}/pkgs/docs.pkg"

	log "three component packages built"
}

# ------------------------------------------------------------------------------------------------
# Step 5 -- the product archive (`productbuild`), and D-13.3's two macOS cells from one component
# ------------------------------------------------------------------------------------------------
# `<domains enable_currentUserHome="true" enable_localSystem="true"/>` is what gives the user the
# per-user/system-wide choice. When they pick "Install for me only", `installer` re-roots every
# component's install-location under their home directory, so:
#
#     /Library/Audio/Plug-Ins/CLAP  ->  ~/Library/Audio/Plug-Ins/CLAP     (D-13.3, macOS row)
#     /Applications                 ->  ~/Applications
#
# `enable_anywhere="false"` because "any volume" would put the plugin somewhere no host scans --
# D-13.3's rationale is that the failure mode of a plugin at an unscanned path is *silent*.
#
# The documents choice is present but not selectable: FR-PKG-040 says every distribution contains
# the attribution file and both licence texts, and a checkbox that can turn that off would make the
# installed product's compliance depend on a user's click.
write_distribution_xml() {
	cat > "${WORK_DIR}/distribution.xml" <<DIST
<?xml version="1.0" encoding="utf-8"?>
<installer-gui-script minSpecVersion="2">
	<title>${PRODUCT_NAME} ${VERSION}</title>
	<organization>${PLUGIN_BUNDLE_ID}</organization>
	<welcome file="welcome.html" mime-type="text/html"/>
	<license file="license.txt" mime-type="text/plain"/>
	<options customize="allow" require-scripts="false" hostArchitectures="arm64,x86_64"/>
	<domains enable_anywhere="false" enable_currentUserHome="true" enable_localSystem="true"/>
	<volume-check>
		<allowed-os-versions>
			<os-version min="${MIN_MACOS_VERSION}"/>
		</allowed-os-versions>
	</volume-check>

	<choices-outline>
		<line choice="choice_plugin"/>
		<line choice="choice_app"/>
		<line choice="choice_docs"/>
	</choices-outline>

	<choice id="choice_plugin" visible="true" title="CLAP plugin"
	        description="${PRODUCT_NAME}.clap, installed to the CLAP search path for the scope you chose.">
		<pkg-ref id="${PKG_ID_PLUGIN}"/>
	</choice>
	<choice id="choice_app" visible="true" title="Standalone application"
	        description="${PRODUCT_NAME}.app.">
		<pkg-ref id="${PKG_ID_APP}"/>
	</choice>
	<choice id="choice_docs" visible="true" enabled="false" selected="true"
	        title="Licences and attribution"
	        description="THIRD-PARTY-NOTICES.md and both licence texts. Always installed.">
		<pkg-ref id="${PKG_ID_DOCS}"/>
	</choice>

	<!-- The leading "#" is what productbuild's own synthesized distribution emits: it names the
	     component package of that name inside the package-path directory, not a URL.
	     NOTE, and read this before editing any comment in this file: the heredoc that writes this
	     document is unquoted, so backticks here are command substitutions, and XML forbids a
	     double hyphen inside a comment. This comment previously contained both. -->
	<pkg-ref id="${PKG_ID_PLUGIN}" version="${VERSION}">#plugin.pkg</pkg-ref>
	<pkg-ref id="${PKG_ID_APP}" version="${VERSION}">#app.pkg</pkg-ref>
	<pkg-ref id="${PKG_ID_DOCS}" version="${VERSION}">#docs.pkg</pkg-ref>
</installer-gui-script>
DIST
}

# The R-11 caveat, in the installer's own welcome pane, shown only when the artifacts are actually
# unsigned. The point of putting it here rather than only in release notes: this is the one screen
# a user reliably sees before the plugin fails to load in their DAW with no message at all.
write_installer_resources() {
	local unsigned_warning=""
	if [ -z "${NAMIR_CODESIGN_IDENTITY:-}" ]; then
		unsigned_warning='<h2 style="color:#b00">This build is not signed or notarised</h2>
		<p>Installing from this package avoids the quarantine flag that a downloaded zip would
		set, which is why Namir ships a <code>.pkg</code>. But the plug-in itself carries no
		Developer ID signature. If it is ever copied or extracted rather than installed, macOS
		will quarantine it, and a quarantined <strong>plug-in</strong> gives you no
		&ldquo;Open Anyway&rdquo; button &mdash; that affordance exists for applications only,
		and macOS&nbsp;15 removed the Control-click bypass. It will simply not appear in your
		host. Treat this build as developer-only.</p>'
	fi

	cat > "${WORK_DIR}/resources/welcome.html" <<WELCOME
<!DOCTYPE html>
<html><head><meta charset="utf-8"></head><body style="font-family:-apple-system,sans-serif">
<h1>${PRODUCT_NAME} ${VERSION}</h1>
<p>A real-time guitar and bass amplifier and cabinet simulator: a Neural Amp Modeler profile, a
cabinet impulse response, a noise gate before the amp and a tone EQ after the cabinet.</p>
<p>This installer places the CLAP plug-in in the CLAP search path, and optionally the standalone
application in Applications. Choosing <em>Install for me only</em> puts both under your home
directory and needs no administrator password.</p>
${unsigned_warning}
</body></html>
WELCOME

	# Both licence texts in full, in the pane the installer makes the user accept. FR-PKG-040 is
	# satisfied by the installed files, not by this pane -- but a dual-licensed product whose
	# installer showed only one of the two would be misleading about its own terms.
	{
		printf '%s is distributed under the terms of the MIT licence OR the Apache License,\n' \
			"$PRODUCT_NAME"
		printf 'Version 2.0, at your option. Both texts follow in full.\n\n'
		printf 'Note: this covers the code. It does not cover the %s name or brand marks --\n' \
			"$PRODUCT_NAME"
		printf 'see TRADEMARK.md in the installed documents.\n\n'
		printf '=== MIT ===\n\n'
		cat "${STAGING}/LICENSE-MIT"
		printf '\n\n=== Apache License 2.0 ===\n\n'
		cat "${STAGING}/LICENSE-APACHE"
	} > "${WORK_DIR}/resources/license.txt"
}

build_product_pkg() {
	step "building ${PKG_NAME}"
	write_distribution_xml
	write_installer_resources

	# The signing-conditional branch, in the form D-18.3 asks for: an argument array that is empty
	# when the secret is absent. `productbuild` is invoked from exactly one place, with exactly one
	# argument list, on both paths. The `${a[@]+"${a[@]}"}` spelling is what makes an empty array
	# expand to nothing under `set -u` on the bash 3.2 macOS ships.
	local sign_args=()
	if [ -n "${NAMIR_INSTALLER_IDENTITY:-}" ]; then
		sign_args=(--sign "${NAMIR_INSTALLER_IDENTITY}")
		log "signing the installer with: ${NAMIR_INSTALLER_IDENTITY}"
	else
		log "NAMIR_INSTALLER_IDENTITY is unset -- the .pkg will be unsigned"
	fi

	# No `--version`/`--identifier` here: `man productbuild` scopes those to its `--component`/
	# `--root` modes, and this is the `--distribution` mode, where each version lives on its own
	# `<pkg-ref>`. Passing them anyway is the kind of thing that either errors or is silently
	# ignored depending on the Xcode version, and neither is worth it.
	productbuild \
		--distribution "${WORK_DIR}/distribution.xml" \
		--package-path "${WORK_DIR}/pkgs" \
		--resources "${WORK_DIR}/resources" \
		${sign_args[@]+"${sign_args[@]}"} \
		"${OUT_DIR}/${PKG_NAME}"

	log "built ${OUT_DIR}/${PKG_NAME}"
}

# ------------------------------------------------------------------------------------------------
# Step 6 -- notarisation (conditional on a secret, same shape as signing)
# ------------------------------------------------------------------------------------------------
# Two submissions, not one: the `.pkg` is notarised and stapled *before* it goes into the `.dmg`,
# and the `.dmg` is notarised and stapled after. Stapling the outer container alone leaves the
# inner package unstapled the moment a user copies it out, and Gatekeeper then needs the network.
#
# Notarisation of an unsigned artifact is rejected by Apple, so this is additionally gated on an
# identity being present -- there is nothing to submit otherwise.
notarize_and_staple() {
	local artifact="$1"

	local notary_args=()
	if [ -n "${NAMIR_NOTARY_PROFILE:-}" ]; then
		notary_args=(--keychain-profile "${NAMIR_NOTARY_PROFILE}")
	elif [ -n "${NAMIR_NOTARY_APPLE_ID:-}" ] && [ -n "${NAMIR_NOTARY_TEAM_ID:-}" ] \
		&& [ -n "${NAMIR_NOTARY_PASSWORD:-}" ]; then
		notary_args=(--apple-id "${NAMIR_NOTARY_APPLE_ID}" \
			--team-id "${NAMIR_NOTARY_TEAM_ID}" \
			--password "${NAMIR_NOTARY_PASSWORD}")
	fi

	if [ ${#notary_args[@]} -eq 0 ] || [ -z "${NAMIR_INSTALLER_IDENTITY:-}${NAMIR_CODESIGN_IDENTITY:-}" ]
	then
		log "no notarisation credentials (or nothing signed) -- skipping for $(basename "$artifact")"
		return 0
	fi

	log "notarising $(basename "$artifact") -- this waits on Apple and can take several minutes"
	xcrun notarytool submit "$artifact" ${notary_args[@]+"${notary_args[@]}"} --wait
	xcrun stapler staple "$artifact"
	xcrun stapler validate "$artifact"
	log "notarised and stapled $(basename "$artifact")"
}

# ------------------------------------------------------------------------------------------------
# Step 7 -- the .dmg
# ------------------------------------------------------------------------------------------------
# The four documents sit at the volume root beside the .pkg as well as inside it. FR-PKG-040 says
# "every distribution, installer and archive alike" -- the .dmg is itself a distribution, and a user
# who mounts it and reads nothing else should still find the notices there.
build_dmg() {
	step "building ${DMG_NAME}"
	rm -rf "${WORK_DIR}/dmg"
	mkdir -p "${WORK_DIR}/dmg"
	ditto "${OUT_DIR}/${PKG_NAME}" "${WORK_DIR}/dmg/${PKG_NAME}"
	local document
	for document in ${STAGED_DOCUMENTS}; do
		ditto "${STAGING}/${document}" "${WORK_DIR}/dmg/${document}"
	done

	rm -f "${OUT_DIR}/${DMG_NAME}"
	# UDZO: compressed, read-only, and the format every macOS since 10.4 mounts without a helper.
	hdiutil create \
		-volname "${PRODUCT_NAME} ${VERSION}" \
		-srcfolder "${WORK_DIR}/dmg" \
		-fs HFS+ \
		-format UDZO \
		-ov \
		"${OUT_DIR}/${DMG_NAME}"

	# A signed .dmg is what lets Gatekeeper evaluate the container before it is opened. Same
	# conditional shape as everything else.
	if [ -n "${NAMIR_CODESIGN_IDENTITY:-}" ]; then
		codesign --force --timestamp --sign "${NAMIR_CODESIGN_IDENTITY}" "${OUT_DIR}/${DMG_NAME}"
	fi

	log "built ${OUT_DIR}/${DMG_NAME}"
}

# ------------------------------------------------------------------------------------------------
# Step 8 -- FR-PKG-050's plain archive: the same artifacts, no installer
# ------------------------------------------------------------------------------------------------
# `ditto -c -k --sequesterRsrc --keepParent` rather than `zip`: it is the only archiver on macOS
# that round-trips a bundle's symlinks, permissions and extended attributes, and `Namir.clap` is a
# bundle. A `zip -r` archive of a .clap produces something that unpacks into a broken plugin.
#
# The honest note this archive carries with it: unzipping it *does* set com.apple.quarantine on
# everything inside, which is the failure mode the .pkg exists to avoid. This archive is for people
# who know that -- FR-PKG-050 is a Should, and D-18.3's reason (b) is why it is not the default.
build_archive() {
	step "building ${ZIP_NAME}"
	rm -rf "${WORK_DIR}/archive"
	mkdir -p "${WORK_DIR}/archive/${PRODUCT_NAME}-${VERSION}"
	local root="${WORK_DIR}/archive/${PRODUCT_NAME}-${VERSION}"

	ditto "${WORK_DIR}/roots/plugin/${CLAP_ARTIFACT}" "${root}/${CLAP_ARTIFACT}"
	ditto "${WORK_DIR}/roots/app/${PRODUCT_NAME}.app" "${root}/${PRODUCT_NAME}.app"
	local document
	for document in ${STAGED_DOCUMENTS}; do
		ditto "${STAGING}/${document}" "${root}/${document}"
	done

	rm -f "${OUT_DIR}/${ZIP_NAME}"
	ditto -c -k --sequesterRsrc --keepParent "$root" "${OUT_DIR}/${ZIP_NAME}"
	log "built ${OUT_DIR}/${ZIP_NAME}"
}

# ------------------------------------------------------------------------------------------------
# Step 9 -- assert the produced distributions, not the plan that produced them
# ------------------------------------------------------------------------------------------------
# FR-PKG-040's method is "the packaging step asserts the presence of all three files in every
# distribution it produces". That is a claim about the .pkg, the .dmg and the .zip, so each is
# opened and looked inside. FR-PKG-020's structural claim is re-checked in the same pass, because
# the bundle that matters is the one that came out, not the one that went in.
#
# NOTE FOR WHOEVER CLOSES FR-PKG-040: this check cannot be its traced artifact. `xtask traceability`
# scans `crates/**`, `xtask/**`, two named workflow files and the root `Cargo.toml`/`deny.toml`
# only (`xtask/src/main.rs`'s scan set); `packaging/**` is not read, so a `# trace:` marker in this
# file would be seen by nothing. The requirement needs an assertion in Rust under `xtask/`.
verify_outputs() {
	if [ "$SKIP_VERIFY" -eq 1 ]; then
		log "--skip-verify given; not opening the produced distributions"
		return 0
	fi
	step "verifying the produced distributions"

	local scratch="${WORK_DIR}/verify"
	rm -rf "$scratch"
	mkdir -p "$scratch"
	local document

	# The .pkg. `--expand-full` unpacks each component's payload as well as its metadata.
	pkgutil --expand-full "${OUT_DIR}/${PKG_NAME}" "${scratch}/pkg"
	# `find … | grep -q` would be the obvious spelling and is wrong under `pipefail`: `grep -q`
	# exits on the first match, `find` takes SIGPIPE, and the pipeline reports failure on success.
	# Capture instead.
	local found
	for document in ${LICENCE_DOCUMENTS}; do
		found="$(find "${scratch}/pkg" -name "$document" -print -quit)"
		[ -n "$found" ] || die "FR-PKG-040: ${document} is not inside ${PKG_NAME}"
	done
	found="$(find "${scratch}/pkg" -type d -name "${CLAP_ARTIFACT}" -print -quit)"
	[ -n "$found" ] || die "FR-PKG-020: ${CLAP_ARTIFACT} is not a directory inside ${PKG_NAME}"
	log "  ${PKG_NAME}: licence documents and the CLAP bundle present"

	# The .dmg, mounted read-only with no Finder window and no browse.
	local mount="${scratch}/mnt"
	mkdir -p "$mount"
	hdiutil attach "${OUT_DIR}/${DMG_NAME}" -readonly -nobrowse -mountpoint "$mount" >/dev/null
	local dmg_ok=1
	for document in ${LICENCE_DOCUMENTS}; do
		[ -f "${mount}/${document}" ] || dmg_ok=0
	done
	[ -f "${mount}/${PKG_NAME}" ] || dmg_ok=0
	hdiutil detach "$mount" -quiet
	[ "$dmg_ok" -eq 1 ] || die "FR-PKG-040/FR-PKG-010: ${DMG_NAME} is missing the .pkg or a licence"
	log "  ${DMG_NAME}: the .pkg and the licence documents present"

	# The .zip.
	ditto -x -k "${OUT_DIR}/${ZIP_NAME}" "${scratch}/zip"
	local unpacked="${scratch}/zip/${PRODUCT_NAME}-${VERSION}"
	for document in ${LICENCE_DOCUMENTS}; do
		[ -f "${unpacked}/${document}" ] || die "FR-PKG-040: ${document} is not inside ${ZIP_NAME}"
	done
	[ -d "${unpacked}/${CLAP_ARTIFACT}" ] \
		|| die "FR-PKG-020: ${CLAP_ARTIFACT} did not survive the archive as a directory"
	[ -f "${unpacked}/${CLAP_ARTIFACT}/Contents/MacOS/${CLAP_DYLIB}" ] \
		|| die "FR-PKG-020: the archived bundle has no ${CLAP_DYLIB}"
	log "  ${ZIP_NAME}: the bundle survived as a bundle, licence documents present"

	rm -rf "$scratch"
}

# NFR-SEC-040's published-hashes half: a hash a user can check is worth having even where
# bit-for-bit reproducibility is not on offer, and it is honest about which of the two this is.
# Written beside each artifact; `release.yml` decides what to do with them.
write_checksums() {
	step "checksums"
	local artifact
	for artifact in "${OUT_DIR}/${PKG_NAME}" "${OUT_DIR}/${DMG_NAME}" "${OUT_DIR}/${ZIP_NAME}"; do
		( cd "$(dirname "$artifact")" && shasum -a 256 "$(basename "$artifact")" \
			| tee "$(basename "$artifact").sha256" )
	done
}

main() {
	require_tools
	mkdir -p "$OUT_DIR"
	log "${PRODUCT_NAME} ${VERSION}"
	log "staging: ${STAGING}"
	log "output:  ${OUT_DIR}"

	verify_staging
	assemble_payloads
	codesign_payloads
	build_component_pkgs
	build_product_pkg
	notarize_and_staple "${OUT_DIR}/${PKG_NAME}"
	build_dmg
	notarize_and_staple "${OUT_DIR}/${DMG_NAME}"
	build_archive
	verify_outputs
	write_checksums

	step "done"
	log "  ${OUT_DIR}/${DMG_NAME}   (the release artifact: a .pkg inside a .dmg)"
	log "  ${OUT_DIR}/${ZIP_NAME}   (FR-PKG-050's plain archive, same artifacts)"
	log "  ${OUT_DIR}/${PKG_NAME}   (the installer alone, for inspection)"

	if [ -z "${NAMIR_CODESIGN_IDENTITY:-}" ] || [ -z "${NAMIR_INSTALLER_IDENTITY:-}" ]; then
		printf '\n'
		log "WARNING -- this build is not fully signed, and risk R-11 applies:"
		log "  a quarantined *plugin* fails to load in a DAW with no user-visible"
		log "  \"Open Anyway\" path. That affordance exists for applications, not plugins,"
		log "  and macOS 15 removed the Control-click bypass. Installing from the .pkg"
		log "  avoids quarantine; extracting the .zip does not."
		log "  Treat this as a developer-only build, and say so in the release notes."
	fi
}

main "$@"
