//! NFR-LIC-050 (Must, `Verify:` **S**): "Test assets in the repository — NAM models, impulse
//! responses, audio signals — shall be either generated by this project or carry a licence
//! permitting redistribution, **recorded in a manifest**."
//!
//! # The manifest the method names did not exist
//!
//! The requirement's traced artifact was `namir-fixtures`, a *runtime generator* whose output is
//! written to a temporary directory and never committed. That is D-19.1's mechanism and it is a
//! good one — but it says nothing about the files that really are checked in, and there are
//! [`ASSET_MANIFEST_PATH`]'s worth of them: fuzz corpora, golden `.nam` models, golden `.wav`
//! renders, `.namirpreset` documents, an f32 input vector, and `namir-ui`'s brand-mark blob.
//! Every one is tracked in git, redistributed with every clone, and recorded nowhere. A captured
//! `.wav` dropped in beside them would breach D-19.1 and AQ-4 with no gate saying a word.
//!
//! This module is the manifest and its check. Same generate-and-diff shape as `params_lock.rs`,
//! including the part that matters most here: the **provenance column is carried forward, never
//! regenerated**, so `--write` cannot silently mint a provenance claim for a file nobody has
//! looked at. A new asset is written as `unrecorded`, and `unrecorded` fails the check.
//!
//! # What is an asset
//!
//! Every file under `crates/` that is not source or build configuration — see
//! [`NON_ASSET_EXTENSIONS`] and [`NON_ASSET_NAMES`]. Deliberately **over**-inclusive: the error
//! direction of a file wrongly required to declare its provenance is one line in a manifest, and
//! the error direction of a file wrongly exempt is the licensing exposure AQ-4 exists to avoid.
//! `namir-ui`'s generated brand blob is in the manifest for that reason, though nothing would call
//! it a test asset.
//!
//! # Residual blind spots, stated rather than pretended closed
//!
//! - **Provenance is a declaration, not a measurement.** Nothing here can tell a generated `.wav`
//!   from a captured one; what the manifest makes impossible is an *undeclared* one. The hash
//!   column is what gives the declaration teeth over time — a file swapped for different bytes
//!   changes its hash, which changes the checked-in manifest, which puts the change in a diff
//!   beside the provenance line someone has to re-read.
//! - **`crates/` only.** `images/` carries the brand artwork, which is Namir's own and is governed
//!   by `TRADEMARK.md` and `xtask identity`'s freshness gate; `docs/` and `packaging/` carry prose.
//!   Widening the walk is a one-line change if either ever gains a data file.
//! - **A `licensed:` entry names an SPDX identifier and nothing more.** There is no check that the
//!   licence text is actually present or that the identifier is one `deny.toml` allows. No entry
//!   uses it today (D-19.1 means none should), so the alternative would be untested machinery.

use std::path::{Path, PathBuf};

/// Where the manifest lives. Under `namir-fixtures` because that crate is D-19.1's generator and
/// so is where a reader looks for the answer to "where did this fixture come from"; `.lock`
/// because it is `params.lock`'s kind of file — generated, checked in, diffed, never hand-edited
/// except in the one column a machine cannot derive.
pub const ASSET_MANIFEST_PATH: &str = "crates/namir-fixtures/assets.lock";

/// The manifest's schema version, written as its `format_version` line.
pub const FORMAT_VERSION: u32 = 1;

/// File extensions that are source or build configuration, not assets.
const NON_ASSET_EXTENSIONS: &[&str] = &["rs", "toml", "lock", "md"];

/// Extensionless files that are configuration rather than assets.
const NON_ASSET_NAMES: &[&str] = &[".gitignore", ".gitattributes"];

/// The provenance token written for an asset no one has yet declared. Fails [`check`] by design.
pub const UNRECORDED: &str = "unrecorded";

const HEADER: &str = "\
# namir test-asset manifest (crates/namir-fixtures/assets.lock) -- NFR-LIC-050: \"Test assets in
# the repository -- NAM models, impulse responses, audio signals -- shall be either generated by
# this project or carry a licence permitting redistribution, recorded in a manifest.\"
#
# Machine-generated except for the provenance column, which is a human declaration and is carried
# forward verbatim by --write. Regenerate with `cargo run -p xtask -- assets --write`, then edit
# any `unrecorded` line to say where that file came from.
#
# Columns: path size-in-bytes blake3 provenance. One line per asset, sorted by path.
# Provenance is `generated` (produced by this project, D-19.1/AQ-4), `licensed:<SPDX>` (a
# third-party asset redistributable under that licence), or `unrecorded` (which fails the gate).
";

/// One asset as the manifest records it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AssetEntry {
    /// Repository-relative, forward slashes, so the manifest is byte-identical on every platform.
    pub path: String,
    pub bytes: u64,
    /// Lowercase hex BLAKE3 of the file's contents — `namir_core::ContentHash`'s own digest, which
    /// is what `namir-library` and `namir-state` already identify a file by.
    pub hash: String,
    pub provenance: String,
}

/// Renders `entries` as manifest text. Sorted by path with a stable sort, so the file never
/// spuriously reorders itself.
pub fn render(entries: &[AssetEntry]) -> String {
    let mut sorted: Vec<&AssetEntry> = entries.iter().collect();
    sorted.sort_by(|a, b| a.path.cmp(&b.path));

    let mut out = String::from(HEADER);
    out.push_str(&format!("format_version {FORMAT_VERSION}\n"));
    for e in sorted {
        out.push_str(&format!(
            "{} {} {} {}\n",
            e.path, e.bytes, e.hash, e.provenance
        ));
    }
    out
}

/// Parses manifest text into entries, ignoring comments and the `format_version` line. A line that
/// does not have four whitespace-separated fields is reported by path-less `Err`; the caller turns
/// that into a violation rather than guessing what was meant.
pub fn parse(text: &str) -> Result<Vec<AssetEntry>, String> {
    let mut entries = Vec::new();
    for (idx, line) in text.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with("format_version") {
            continue;
        }
        let fields: Vec<&str> = trimmed.split_whitespace().collect();
        let [path, bytes, hash, provenance] = fields.as_slice() else {
            return Err(format!("line {}: not four fields: '{line}'", idx + 1));
        };
        let bytes = bytes
            .parse::<u64>()
            .map_err(|_| format!("line {}: '{bytes}' is not a byte count", idx + 1))?;
        entries.push(AssetEntry {
            path: (*path).to_string(),
            bytes,
            hash: (*hash).to_string(),
            provenance: (*provenance).to_string(),
        });
    }
    Ok(entries)
}

/// Whether `path`'s file name marks it as source or build configuration rather than an asset.
fn is_non_asset(path: &Path) -> bool {
    if let Some(name) = path.file_name().and_then(|n| n.to_str())
        && NON_ASSET_NAMES.contains(&name)
    {
        return true;
    }
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|ext| NON_ASSET_EXTENSIONS.contains(&ext))
}

/// Every asset under `<repo_root>/crates`, hashed, with `provenance` taken from `previous` where a
/// path is already recorded there and [`UNRECORDED`] where it is not.
///
/// Carrying provenance forward rather than deriving it is the whole point (see the module doc):
/// `--write` must not be able to mint a claim about a file's origin. A path whose *bytes* have
/// changed keeps its declaration — the hash column moves, which is what puts the change in front of
/// a reviewer beside the line they would have to re-affirm.
pub fn scan(repo_root: &Path, previous: &[AssetEntry]) -> Result<Vec<AssetEntry>, String> {
    let crates_dir = repo_root.join("crates");
    let mut entries = Vec::new();

    for file in walkdir::WalkDir::new(&crates_dir)
        .into_iter()
        .filter_entry(|e| e.file_name() != "target")
        .filter_map(Result::ok)
        .filter(|e| e.file_type().is_file())
    {
        let path = file.path();
        if is_non_asset(path) {
            continue;
        }
        let rel = path
            .strip_prefix(repo_root)
            .map_err(|e| format!("{}: {e}", path.display()))?
            .to_string_lossy()
            .replace('\\', "/");
        let bytes = std::fs::read(path).map_err(|e| format!("{}: {e}", path.display()))?;
        let provenance = previous
            .iter()
            .find(|p| p.path == rel)
            .map_or(UNRECORDED.to_string(), |p| p.provenance.clone());
        entries.push(AssetEntry {
            path: rel,
            bytes: bytes.len() as u64,
            hash: namir_core::ContentHash::of(&bytes).to_string(),
            provenance,
        });
    }

    Ok(entries)
}

/// The manifest's own rule set, applied to `recorded` (what the file says) against `actual` (what
/// the tree holds). Returns one message per problem — empty means clean.
///
/// Kept separate from the text diff so the failure a reader sees names the *asset*, not a line
/// number: "this file's provenance is unrecorded" is actionable where "the manifest is stale" is
/// only the first half of a sentence.
pub fn violations(recorded: &[AssetEntry], actual: &[AssetEntry]) -> Vec<String> {
    let mut out = Vec::new();

    for entry in actual {
        match recorded.iter().find(|r| r.path == entry.path) {
            None => out.push(format!(
                "{}: not in the manifest -- every checked-in asset must declare where it came \
                 from (NFR-LIC-050). Run `cargo run -p xtask -- assets --write`, then replace the \
                 new line's `{UNRECORDED}` with `generated` or `licensed:<SPDX>`",
                entry.path
            )),
            Some(r) if r.provenance == UNRECORDED => out.push(format!(
                "{}: provenance is `{UNRECORDED}` -- declare it as `generated` (D-19.1: fixtures \
                 are generated from a seed, never captured) or `licensed:<SPDX>`",
                entry.path
            )),
            Some(r) if r.hash != entry.hash || r.bytes != entry.bytes => out.push(format!(
                "{}: contents changed since the manifest was written ({} bytes / {}... recorded, \
                 {} bytes / {}... on disk). Regenerate with `--write` and re-read the provenance \
                 line beside it",
                entry.path,
                r.bytes,
                &r.hash[..r.hash.len().min(12)],
                entry.bytes,
                &entry.hash[..entry.hash.len().min(12)],
            )),
            Some(_) => {}
        }
    }

    for entry in recorded {
        if !actual.iter().any(|a| a.path == entry.path) {
            out.push(format!(
                "{}: recorded in the manifest but no longer in the tree -- regenerate with \
                 `--write`",
                entry.path
            ));
        }
    }

    out
}

/// Reads the manifest under `repo_root` (an absent one parses as empty, which is the
/// first-generation case), scans the tree, and either reports violations or regenerates.
///
/// `Ok(violations)` — empty means the gate passes. `Err` is a check that could not run.
pub fn check_or_write(repo_root: &Path, write: bool) -> Result<Vec<String>, String> {
    let manifest_path: PathBuf = repo_root.join(ASSET_MANIFEST_PATH);
    let text = std::fs::read_to_string(&manifest_path).unwrap_or_default();
    let recorded = parse(&text).map_err(|e| format!("{}: {e}", manifest_path.display()))?;
    let actual = scan(repo_root, &recorded)?;

    if write {
        let rendered = render(&actual);
        if let Some(parent) = manifest_path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("failed to create {}: {e}", parent.display()))?;
        }
        std::fs::write(&manifest_path, &rendered)
            .map_err(|e| format!("failed to write {}: {e}", manifest_path.display()))?;
        // Still reported after a write: `--write` fills in paths, sizes and hashes, and can never
        // fill in a provenance. A regeneration that went green while leaving `unrecorded` lines
        // behind would be the one-flag bypass `params-lock`'s own gate refuses.
        return Ok(violations(&parse(&rendered)?, &actual));
    }

    let mut out = violations(&recorded, &actual);
    // The text diff too, so a reordering or a hand-edit of the generated columns is caught even
    // when every entry is individually in order.
    if out.is_empty() && text != render(&actual) {
        out.push(format!(
            "{} does not match a fresh render of itself -- regenerate it with `cargo run -p xtask \
             -- assets --write` (the provenance column is carried forward unchanged)",
            manifest_path.display()
        ));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(path: &str, provenance: &str) -> AssetEntry {
        AssetEntry {
            path: path.to_string(),
            bytes: 3,
            hash: namir_core::ContentHash::of(b"abc").to_string(),
            provenance: provenance.to_string(),
        }
    }

    #[test]
    fn render_and_parse_round_trip() {
        let entries = vec![
            entry("crates/b/x.wav", "generated"),
            entry("crates/a/y.nam", "generated"),
        ];
        let text = render(&entries);
        let parsed = parse(&text).unwrap();
        // Sorted by path on render, so the round trip normalises order.
        assert_eq!(parsed[0].path, "crates/a/y.nam");
        assert_eq!(parsed[1].path, "crates/b/x.wav");
        assert_eq!(render(&parsed), text);
    }

    #[test]
    fn a_malformed_line_is_an_error_not_a_silent_drop() {
        assert!(parse("format_version 1\ncrates/a/x.wav 3\n").is_err());
        assert!(parse("format_version 1\ncrates/a/x.wav notanumber h generated\n").is_err());
    }

    #[test]
    fn source_and_configuration_files_are_not_assets() {
        for name in [
            "lib.rs",
            "Cargo.toml",
            "Cargo.lock",
            "README.md",
            ".gitignore",
        ] {
            assert!(is_non_asset(Path::new(name)), "{name}");
        }
        for name in [
            "valid_delta.wav",
            "wavenet_nano.nam",
            "input.f32",
            "mutated_0.bin",
        ] {
            assert!(!is_non_asset(Path::new(name)), "{name}");
        }
    }

    #[test]
    fn an_asset_missing_from_the_manifest_is_a_violation() {
        let actual = vec![entry("crates/a/new.wav", UNRECORDED)];
        let problems = violations(&[], &actual);
        assert_eq!(problems.len(), 1, "{problems:#?}");
        assert!(problems[0].contains("not in the manifest"), "{problems:#?}");
    }

    #[test]
    fn an_unrecorded_provenance_is_a_violation() {
        let entries = vec![entry("crates/a/new.wav", UNRECORDED)];
        let problems = violations(&entries, &entries);
        assert_eq!(problems.len(), 1, "{problems:#?}");
        assert!(problems[0].contains("provenance is"), "{problems:#?}");
    }

    #[test]
    fn a_changed_asset_is_a_violation_even_though_its_path_is_recorded() {
        // The teeth on the provenance declaration: swapping a generated fixture for a captured
        // file of the same name changes the hash, which forces the manifest -- and the provenance
        // line beside it -- back into the diff.
        let recorded = vec![entry("crates/a/x.wav", "generated")];
        let mut actual = recorded.clone();
        actual[0].hash = namir_core::ContentHash::of(b"different").to_string();
        let problems = violations(&recorded, &actual);
        assert_eq!(problems.len(), 1, "{problems:#?}");
        assert!(problems[0].contains("contents changed"), "{problems:#?}");
    }

    #[test]
    fn a_deleted_asset_still_recorded_is_a_violation() {
        let problems = violations(&[entry("crates/a/gone.wav", "generated")], &[]);
        assert_eq!(problems.len(), 1, "{problems:#?}");
        assert!(
            problems[0].contains("no longer in the tree"),
            "{problems:#?}"
        );
    }

    #[test]
    fn a_declared_asset_that_matches_is_clean() {
        let entries = vec![entry("crates/a/x.wav", "generated")];
        assert!(violations(&entries, &entries).is_empty());
    }

    /// A scratch repo root with one asset under `crates/`.
    fn scratch(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("xtask-assets-{name}-{}", std::process::id()));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(dir.join("crates/namir-ir/fuzz/corpus/probe_wav")).unwrap();
        std::fs::write(
            dir.join("crates/namir-ir/fuzz/corpus/probe_wav/valid_delta.wav"),
            b"RIFF....WAVE",
        )
        .unwrap();
        std::fs::write(dir.join("crates/namir-ir/Cargo.toml"), "[package]\n").unwrap();
        dir
    }

    #[test]
    fn write_records_a_new_asset_as_unrecorded_and_still_reports_it() {
        // `--write` must not be a one-flag bypass: it fills in the columns a machine can derive and
        // leaves -- and reports -- the one it cannot.
        let dir = scratch("write");
        let problems = check_or_write(&dir, true).unwrap();
        assert_eq!(problems.len(), 1, "{problems:#?}");
        assert!(problems[0].contains("provenance is"), "{problems:#?}");

        let text = std::fs::read_to_string(dir.join(ASSET_MANIFEST_PATH)).unwrap();
        assert!(text.contains("valid_delta.wav"), "{text}");
        assert!(text.contains(UNRECORDED), "{text}");

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn a_declared_manifest_round_trips_green_and_keeps_its_provenance() {
        let dir = scratch("declared");
        check_or_write(&dir, true).unwrap();
        let path = dir.join(ASSET_MANIFEST_PATH);
        // Only the provenance column: the header comment names `unrecorded` too, and rewriting it
        // there would make the manifest differ from a fresh render for a reason unrelated to the
        // property under test.
        let declared = std::fs::read_to_string(&path)
            .unwrap()
            .replace(&format!(" {UNRECORDED}\n"), " generated\n");
        std::fs::write(&path, &declared).unwrap();

        assert!(check_or_write(&dir, false).unwrap().is_empty());

        // And a second `--write` carries the human declaration forward rather than resetting it.
        assert!(check_or_write(&dir, true).unwrap().is_empty());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), declared);

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn an_asset_added_beside_the_declared_ones_fails_the_check() {
        // The scenario NFR-LIC-050 exists for: a captured `.wav` dropped into the corpus.
        let dir = scratch("added");
        check_or_write(&dir, true).unwrap();
        let path = dir.join(ASSET_MANIFEST_PATH);
        // Only the provenance column: the header comment names `unrecorded` too, and rewriting it
        // there would make the manifest differ from a fresh render for a reason unrelated to the
        // property under test.
        let declared = std::fs::read_to_string(&path)
            .unwrap()
            .replace(&format!(" {UNRECORDED}\n"), " generated\n");
        std::fs::write(&path, declared).unwrap();
        assert!(check_or_write(&dir, false).unwrap().is_empty());

        std::fs::write(
            dir.join("crates/namir-ir/fuzz/corpus/probe_wav/captured_cab.wav"),
            b"RIFF-someone-elses-recording",
        )
        .unwrap();
        let problems = check_or_write(&dir, false).unwrap();
        assert_eq!(problems.len(), 1, "{problems:#?}");
        assert!(problems[0].contains("captured_cab.wav"), "{problems:#?}");

        std::fs::remove_dir_all(&dir).ok();
    }
}
