//! NFR-LIC-030 (Must): "A machine-generated attribution file listing every dependency and its
//! licence shall be produced by the build and shipped with the binaries." Same generate-and-diff
//! shape as `params_lock.rs`: [`crate::cargo_meta::third_party_runtime_dependencies`] is the
//! source of truth (every third-party crate reachable from `namir-app`/`namir-clap` -- the two
//! shipped products -- by an all-`Normal`-dependency-kind path), [`render`] turns it into
//! deterministic text, and [`check_or_write`] diffs that text against the checked-in
//! `THIRD-PARTY-NOTICES.md`, or regenerates it with `--write`.
//!
//! Scope note, recorded rather than silently assumed: this closes *production* of the artifact
//! and its CI-gated freshness. Physically bundling it into a release installer/zip is a packaging
//! concern with no pipeline yet (that's M8 territory, docs/03-implementation-roadmap.md §12) --
//! this file does not claim to close that half.

use std::path::Path;

use crate::cargo_meta;

/// One third-party dependency's attribution line. Deliberately not `cargo_metadata::Package`
/// itself -- keeping this module's own type small and plain lets [`render`] stay unit-testable
/// against synthetic data with no `cargo metadata` invocation involved, the same separation
/// `layering.rs` keeps from `cargo_meta.rs`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct ThirdPartyDep {
    pub name: String,
    pub version: String,
    pub license: String,
}

const HEADER: &str = "\
# Third-party notices

Machine-generated by `cargo run -p xtask -- attribution --write` (NFR-LIC-030). Do not hand-edit --
regenerate instead. Lists every third-party crate reachable from `namir-app` and `namir-clap` (the
two shipped products) via a path of only `Normal`-kind dependency edges -- dev-only and build-only
subtrees (test fixtures, benchmark tooling, this repository's own dev tooling) are excluded because
they are never linked into a release binary.

| Crate | Version | Licence |
|---|---|---|
";

/// Renders `deps` (expected pre-sorted by `(name, version)`, as
/// [`cargo_meta::third_party_runtime_dependencies`] already returns them) into the checked-in
/// file's exact text.
pub fn render(deps: &[ThirdPartyDep]) -> String {
    let mut out = String::from(HEADER);
    for dep in deps {
        out.push_str(&format!(
            "| {} | {} | {} |\n",
            dep.name, dep.version, dep.license
        ));
    }
    out
}

/// Compares `THIRD-PARTY-NOTICES.md` under `repo_root` against a fresh
/// `third_party_runtime_dependencies` run. Same `(up_to_date, message)` / `--write` contract as
/// `params_lock::check_or_write`.
pub fn check_or_write(repo_root: &Path, write: bool) -> Result<(bool, String), String> {
    let deps = cargo_meta::third_party_runtime_dependencies(repo_root)?;
    let expected = render(&deps);
    let notices_path = repo_root.join("THIRD-PARTY-NOTICES.md");

    if write {
        std::fs::write(&notices_path, &expected)
            .map_err(|e| format!("failed to write {}: {e}", notices_path.display()))?;
        return Ok((
            true,
            format!(
                "wrote {} ({} dependencies)",
                notices_path.display(),
                deps.len()
            ),
        ));
    }

    let actual = std::fs::read_to_string(&notices_path)
        .map_err(|e| format!("failed to read {}: {e}", notices_path.display()))?;

    if actual == expected {
        return Ok((true, format!("{} is up to date", notices_path.display())));
    }

    Ok((
        false,
        format!(
            "{} is stale -- does not match the current dependency graph. Run \
             `cargo run -p xtask -- attribution --write` to regenerate it.",
            notices_path.display()
        ),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dep(name: &str, version: &str, license: &str) -> ThirdPartyDep {
        ThirdPartyDep {
            name: name.to_string(),
            version: version.to_string(),
            license: license.to_string(),
        }
    }

    #[test]
    fn render_is_empty_table_for_no_dependencies() {
        let text = render(&[]);
        assert!(text.contains("| Crate | Version | Licence |"));
        assert!(!text.contains("\n| \n"));
    }

    #[test]
    fn render_lists_each_dependency_as_a_table_row() {
        let deps = vec![
            dep("serde", "1.0.0", "MIT OR Apache-2.0"),
            dep("hound", "3.5.0", "Apache-2.0"),
        ];
        let text = render(&deps);
        assert!(text.contains("| serde | 1.0.0 | MIT OR Apache-2.0 |"));
        assert!(text.contains("| hound | 3.5.0 | Apache-2.0 |"));
    }

    #[test]
    fn render_is_deterministic() {
        let deps = vec![dep("a", "1.0.0", "MIT")];
        assert_eq!(render(&deps), render(&deps));
    }
}
